/**
 * Nepal's federal administrative divisions: 7 provinces, 77 districts and the
 * 753 local levels (6 metropolitan cities, 11 sub-metropolitan cities,
 * 276 municipalities, 460 rural municipalities).
 *
 * Source: https://github.com/sagautam5/local-states-nepal (dataset/, MIT),
 * itself compiled from Wikipedia and Nepali government sources. Two changes
 * were applied when generating this file:
 *
 *   1. "काेशी प्रदेश" was written with ा + े instead of ो, and is corrected here.
 *   2. The source romanises बुढानिलकण्ठ as "Budhalikantha"; the local body's own
 *      site (budhanilkanthamun.gov.np) uses "Budhanilkantha", which is used here.
 *
 * Names are stored the way they are displayed and saved: municipalities carry
 * their category suffix ("Kathmandu Metropolitan City"), while provinces and
 * districts are bare ("Bagmati", "Kathmandu"). That matches the values already
 * in the properties table.
 */

export type MunicipalityType =
  | "metropolitan"
  | "sub_metropolitan"
  | "municipality"
  | "rural";

export type Municipality = {
  name: string;
  nameNp: string;
  type: MunicipalityType;
  /** Number of wards, useful for bounding the ward input. */
  wards: number;
};

export type District = {
  name: string;
  nameNp: string;
  municipalities: Municipality[];
};

export type Province = {
  name: string;
  nameNp: string;
  districts: District[];
};

export const PROVINCES: Province[] = [
  {
    name: "Koshi",
    nameNp: "कोशी",
    districts: [
      {
        name: "Bhojpur",
        nameNp: "भोजपुर",
        municipalities: [
          { name: "Aamchok Rural Municipality", nameNp: "आमचोक गाउँपालिका", type: "rural", wards: 10 },
          { name: "Arun Rural Municipality", nameNp: "अरुण गाउँपालिका", type: "rural", wards: 7 },
          { name: "Bhojpur Municipality", nameNp: "भोजपुर नगरपालिका", type: "municipality", wards: 12 },
          { name: "Hatuwagadhi Rural Municipality", nameNp: "हतुवागढी गाउँपालिका", type: "rural", wards: 9 },
          { name: "Pauwadungma Rural Municipality", nameNp: "पौवादुङमा गाउँपालिका", type: "rural", wards: 6 },
          { name: "Ramprasad Rai Rural Municipality", nameNp: "रामप्रसाद राई गाउँपालिका", type: "rural", wards: 8 },
          { name: "Salpasilichho Rural Municipality", nameNp: "साल्पासिलिछो गाउँपालिका", type: "rural", wards: 6 },
          { name: "Shadanand Municipality", nameNp: "षडानन्द नगरपालिका", type: "municipality", wards: 14 },
          { name: "Tyamke Maiyum Rural Municipality", nameNp: "टेम्केमैयुङ गाउँपालिका", type: "rural", wards: 9 },
        ],
      },
      {
        name: "Dhankuta",
        nameNp: "धनकुटा",
        municipalities: [
          { name: "Chaubise Rural Municipality", nameNp: "चौविसे गाउँपालिका", type: "rural", wards: 8 },
          { name: "Chhathar Jorpati Rural Municipality", nameNp: "छथर जोरपाटी गाउँपालिका", type: "rural", wards: 6 },
          { name: "Dhankuta Municipality", nameNp: "धनकुटा नगरपालिका", type: "municipality", wards: 10 },
          { name: "Mahalaxmi Municipality", nameNp: "महालक्ष्मी नगरपालिका", type: "municipality", wards: 9 },
          { name: "Pakhribas Municipality", nameNp: "पाख्रिबास नगरपालिका", type: "municipality", wards: 10 },
          { name: "Sahidbhumi Rural Municipality", nameNp: "सहिदभूमि गाउँपालिका", type: "rural", wards: 7 },
          { name: "Sangurigadhi Rural Municipality", nameNp: "साँगुरीगढी गाउँपालिका", type: "rural", wards: 10 },
        ],
      },
      {
        name: "Ilam",
        nameNp: "इलाम",
        municipalities: [
          { name: "Chulachuli Rural Municipality", nameNp: "चुलाचुली गाउँपालिका", type: "rural", wards: 6 },
          { name: "Deumai Municipality", nameNp: "देउमाई नगरपालिका", type: "municipality", wards: 9 },
          { name: "Ilam Municipality", nameNp: "ईलाम नगरपालिका", type: "municipality", wards: 12 },
          { name: "Mai Municipality", nameNp: "माई नगरपालिका", type: "municipality", wards: 10 },
          { name: "Maijogmai Rural Municipality", nameNp: "माईजोगमाई गाउँपालिका", type: "rural", wards: 6 },
          { name: "Mangsebung Rural Municipality", nameNp: "माङसेबुङ गाउँपालिका", type: "rural", wards: 6 },
          { name: "Phakphokthum Rural Municipality", nameNp: "फाकफोकथुम गाउँपालिका", type: "rural", wards: 7 },
          { name: "Rong Rural Municipality", nameNp: "रोङ गाउँपालिका", type: "rural", wards: 6 },
          { name: "Sandakpur Rural Municipality", nameNp: "सन्दकपुर गाउँपालिका", type: "rural", wards: 5 },
          { name: "Suryodaya Municipality", nameNp: "सूर्योदय नगरपालिका", type: "municipality", wards: 14 },
        ],
      },
      {
        name: "Jhapa",
        nameNp: "झापा",
        municipalities: [
          { name: "Arjundhara Municipality", nameNp: "अर्जुनधारा नगरपालिका", type: "municipality", wards: 11 },
          { name: "Barhadashi Rural Municipality", nameNp: "बाह्रदशी गाउँपालिका", type: "rural", wards: 7 },
          { name: "Bhadrapur Municipality", nameNp: "भद्रपुर नगरपालिका", type: "municipality", wards: 10 },
          { name: "Birtamod Municipality", nameNp: "विर्तामोड नगरपालिका", type: "municipality", wards: 10 },
          { name: "Buddha Shanti Rural Municipality", nameNp: "बुद्धशान्ति गाउँपालिका", type: "rural", wards: 7 },
          { name: "Damak Municipality", nameNp: "दमक नगरपालिका", type: "municipality", wards: 10 },
          { name: "Gauradaha Municipality", nameNp: "गौरादह नगरपालिका", type: "municipality", wards: 9 },
          { name: "Gaurigunj Rural Municipality", nameNp: "गौरीगंज गाउँपालिका", type: "rural", wards: 6 },
          { name: "Haldibari Rural Municipality", nameNp: "हल्दिवारी गाउँपालिका", type: "rural", wards: 5 },
          { name: "Jhapa Rural Municipality", nameNp: "झापा गाउँपालिका", type: "rural", wards: 7 },
          { name: "Kachankawal Rural Municipality", nameNp: "कचनकवल गाउँपालिका", type: "rural", wards: 7 },
          { name: "Kamal Rural Municipality", nameNp: "कमल गाउँपालिका", type: "rural", wards: 7 },
          { name: "Kankai Municipality", nameNp: "कन्काई नगरपालिका", type: "municipality", wards: 9 },
          { name: "Mechinagar Municipality", nameNp: "मेचीनगर नगरपालिका", type: "municipality", wards: 15 },
          { name: "Shivasatakshi Municipality", nameNp: "शिवशताक्षी नगरपालिका", type: "municipality", wards: 11 },
        ],
      },
      {
        name: "Khotang",
        nameNp: "खोटाँग",
        municipalities: [
          { name: "Aiselukharka Rural Municipality", nameNp: "ऐसेलुखर्क गाउँपालिका", type: "rural", wards: 7 },
          { name: "Barahpokhari Rural Municipality", nameNp: "वराहपोखरी गाउँपालिका", type: "rural", wards: 6 },
          { name: "Diktel Rupakot Majhuwagadhi Municipality", nameNp: "दिक्तेल रुपाकोट मझुवागढी नगरपालिका", type: "municipality", wards: 15 },
          { name: "Diprung Chuichumma Rural Municipality", nameNp: "दिप्रुङ चुइचुम्मा गाउँपालिका", type: "rural", wards: 7 },
          { name: "Halesi Tuwachung Municipality", nameNp: "हलेसी तुवाचुङ नगरपालिका", type: "municipality", wards: 11 },
          { name: "Jantedhunga Rural Municipality", nameNp: "जन्तेढुंगा गाउँपालिका", type: "rural", wards: 6 },
          { name: "Kepilasgadhi Rural Municipality", nameNp: "केपिलासगढी गाउँपालिका", type: "rural", wards: 7 },
          { name: "Khotehang Rural Municipality", nameNp: "खोटेहाङ गाउँपालिका", type: "rural", wards: 9 },
          { name: "Rawa Besi Rural Municipality", nameNp: "रावा बेसी गाउँपालिका", type: "rural", wards: 6 },
          { name: "Sakela Rural Municipality", nameNp: "साकेला गाउँपालिका", type: "rural", wards: 5 },
        ],
      },
      {
        name: "Morang",
        nameNp: "मोरंग",
        municipalities: [
          { name: "Belbari Municipality", nameNp: "बेलवारी नगरपालिका", type: "municipality", wards: 11 },
          { name: "Biratnagar Metropolitan City", nameNp: "विराटनगर महानगरपालिका", type: "metropolitan", wards: 19 },
          { name: "Budi Ganga Rural Municipality", nameNp: "बुढीगंगा गाउँपालिका", type: "rural", wards: 7 },
          { name: "Dhanpalthan Rural Municipality", nameNp: "धनपालथान गाउँपालिका", type: "rural", wards: 7 },
          { name: "Gramthan Rural Municipality", nameNp: "ग्रामथान गाउँपालिका", type: "rural", wards: 7 },
          { name: "Jahada Rural Municipality", nameNp: "जहदा गाउँपालिका", type: "rural", wards: 7 },
          { name: "Kanepokhari Rural Municipality", nameNp: "कानेपोखरी गाउँपालिका", type: "rural", wards: 7 },
          { name: "Katahari Rural Municipality", nameNp: "कटहरी गाउँपालिका", type: "rural", wards: 7 },
          { name: "Kerabari Rural Municipality", nameNp: "केरावारी गाउँपालिका", type: "rural", wards: 10 },
          { name: "Letang Municipality", nameNp: "लेटाङ नगरपालिका", type: "municipality", wards: 9 },
          { name: "Miklajung Rural Municipality", nameNp: "मिक्लाजुङ गाउँपालिका", type: "rural", wards: 9 },
          { name: "Pathari Shanischare Municipality", nameNp: "पथरी शनिश्चरे नगरपालिका", type: "municipality", wards: 10 },
          { name: "Rangeli Municipality", nameNp: "रंगेली नगरपालिका", type: "municipality", wards: 9 },
          { name: "Ratuwamai Municipality", nameNp: "रतुवामाई नगरपालिका", type: "municipality", wards: 10 },
          { name: "Sunawarshi Municipality", nameNp: "सुनवर्षि नगरपालिका", type: "municipality", wards: 9 },
          { name: "Sundar Haraicha Municipality", nameNp: "सुन्दरहरैचा नगरपालिका", type: "municipality", wards: 12 },
          { name: "Urlabari Municipality", nameNp: "उर्लावारी नगरपालिका", type: "municipality", wards: 9 },
        ],
      },
      {
        name: "Okhaldhunga",
        nameNp: "ओखलढुंगा",
        municipalities: [
          { name: "Champadevi Rural Municipality", nameNp: "चम्पादेवी गाउँपालिका", type: "rural", wards: 10 },
          { name: "Chisankhugadhi Rural Municipality", nameNp: "चिशंखुगढी गाउँपालिका", type: "rural", wards: 8 },
          { name: "Khiji Demba Rural Municipality", nameNp: "खिजिदेम्बा गाउँपालिका", type: "rural", wards: 9 },
          { name: "Likhu Rural Municipality", nameNp: "लिखु गाउँपालिका", type: "rural", wards: 9 },
          { name: "Manebhanjyang Rural Municipality", nameNp: "मानेभञ्याङ गाउँपालिका", type: "rural", wards: 9 },
          { name: "Molung Rural Municipality", nameNp: "मोलुङ गाउँपालिका", type: "rural", wards: 8 },
          { name: "Siddhicharan Municipality", nameNp: "सिद्दिचरण नगरपालिका", type: "municipality", wards: 12 },
          { name: "Sunkoshi Rural Municipality", nameNp: "सुनकोशी गाउँपालिका", type: "rural", wards: 10 },
        ],
      },
      {
        name: "Pachthar",
        nameNp: "पांचथर",
        municipalities: [
          { name: "Hilihang Rural Municipality", nameNp: "हिलिहाङ गाउँपालिका", type: "rural", wards: 7 },
          { name: "Kummayak Rural Municipality", nameNp: "कुम्मायक गाउँपालिका", type: "rural", wards: 5 },
          { name: "Miklajung Rural Municipality", nameNp: "मिक्लाजुङ गाउँपालिका", type: "rural", wards: 8 },
          { name: "Phalelung Rural Municipality", nameNp: "फालेलुङ गाउँपालिका", type: "rural", wards: 8 },
          { name: "Phalgunanda Rural Municipality", nameNp: "फाल्गुनन्द गाउँपालिका", type: "rural", wards: 7 },
          { name: "Phidim Municipality", nameNp: "फिदिम नगरपालिका", type: "municipality", wards: 14 },
          { name: "Tumbewa Rural Municipality", nameNp: "तुम्बेवा गाउँपालिका", type: "rural", wards: 5 },
          { name: "Yangwarak Rural Municipality", nameNp: "याङवरक गाउँपालिका", type: "rural", wards: 6 },
        ],
      },
      {
        name: "Sankhuwasabha",
        nameNp: "संखुवासभा",
        municipalities: [
          { name: "BhotKhola Rural Municipality", nameNp: "भोटखोला गाउँपालिका", type: "rural", wards: 5 },
          { name: "Chainpur Municipality", nameNp: "चैनपुर नगरपालिका", type: "municipality", wards: 11 },
          { name: "Chichila Rural Municipality", nameNp: "चिचिला गाउँपालिका", type: "rural", wards: 5 },
          { name: "Dharmadevi Municipality", nameNp: "धर्मदेवी नगरपालिका", type: "municipality", wards: 9 },
          { name: "Khandbari Municipality", nameNp: "खाँदवारी नगरपालिका", type: "municipality", wards: 11 },
          { name: "Madi Municipality", nameNp: "मादी नगरपालिका", type: "municipality", wards: 9 },
          { name: "Makalu Rural Municipality", nameNp: "मकालु गाउँपालिका", type: "rural", wards: 6 },
          { name: "Panchkhapan Municipality", nameNp: "पाँचखपन नगरपालिका", type: "municipality", wards: 9 },
          { name: "Sabhapokhari Rural Municipality", nameNp: "सभापोखरी गाउँपालिका", type: "rural", wards: 6 },
          { name: "Silichong Rural Municipality", nameNp: "सिलीचोङ गाउँपालिका", type: "rural", wards: 5 },
        ],
      },
      {
        name: "Solukhumbu",
        nameNp: "सोलुखुम्बू",
        municipalities: [
          { name: "Khumbu PasangLhamu Rural Municipality", nameNp: "खुम्वु पासाङल्हमु गाउँपालिका", type: "rural", wards: 5 },
          { name: "Likhu Pike Rural Municipality", nameNp: "लिखु पिके गाउँपालिका", type: "rural", wards: 5 },
          { name: "Maha Kulung Rural Municipality", nameNp: "माहाकुलुङ गाउँपालिका", type: "rural", wards: 5 },
          { name: "Mapya Dudhkoshi Rural Municipality", nameNp: "माप्य दुधकोशी गाउँपालिका", type: "rural", wards: 7 },
          { name: "Necha Salyan Rural Municipality", nameNp: "नेचासल्यान गाउँपालिका", type: "rural", wards: 5 },
          { name: "Solu Dudhkunda Municipality", nameNp: "सोलुदुधकुण्ड नगरपालिका", type: "municipality", wards: 11 },
          { name: "Sotang Rural Municipality", nameNp: "सोताङ गाउँपालिका", type: "rural", wards: 5 },
          { name: "Thulung Dudhkoshi Rural Municipality", nameNp: "थुलुङ दुधकोशी गाउँपालिका", type: "rural", wards: 9 },
        ],
      },
      {
        name: "Sunsari",
        nameNp: "सुनसरी",
        municipalities: [
          { name: "BarahaKshetra Municipality", nameNp: "बराहक्षेत्र नगरपालिका", type: "municipality", wards: 11 },
          { name: "Barju Rural Municipality", nameNp: "बर्जु गाउँपालिका", type: "rural", wards: 6 },
          { name: "Bhokraha Narsingh Rural Municipality", nameNp: "भोक्राहा नरसिंह गाउँपालिका", type: "rural", wards: 8 },
          { name: "Dewangunj Rural Municipality", nameNp: "देवानगञ्ज गाउँपालिका", type: "rural", wards: 7 },
          { name: "Dharan Sub-Metropolitan City", nameNp: "धरान उपमहानगरपालिका", type: "sub_metropolitan", wards: 20 },
          { name: "Duhabi Municipality", nameNp: "दुहवी नगरपालिका", type: "municipality", wards: 12 },
          { name: "Gadhi Rural Municipality", nameNp: "गढी गाउँपालिका", type: "rural", wards: 6 },
          { name: "Harinagar Rural Municipality", nameNp: "हरिनगर गाउँपालिका", type: "rural", wards: 7 },
          { name: "Inaruwa Municipality", nameNp: "ईनरुवा नगरपालिका", type: "municipality", wards: 10 },
          { name: "Itahari Sub-Metropolitan City", nameNp: "ईटहरी उपमहानगरपालिका", type: "sub_metropolitan", wards: 20 },
          { name: "Koshi Rural Municipality", nameNp: "कोशी गाउँपालिका", type: "rural", wards: 8 },
          { name: "Ramdhuni Municipality", nameNp: "रामधुनी नगरपालिका", type: "municipality", wards: 9 },
        ],
      },
      {
        name: "Taplejung",
        nameNp: "ताप्लेजुंग",
        municipalities: [
          { name: "Aathrai Triveni Rural Municipality", nameNp: "आठराई त्रिवेणी गाउँपालिका", type: "rural", wards: 5 },
          { name: "Maiwa Khola Rural Municipality", nameNp: "मैवाखोला गाउँपालिका", type: "rural", wards: 6 },
          { name: "Meringden Rural Municipality", nameNp: "मेरिङदेन गाउँपालिका", type: "rural", wards: 6 },
          { name: "Mikwa Khola Rural Municipality", nameNp: "मिक्वाखोला गाउँपालिका", type: "rural", wards: 5 },
          { name: "Pathibhara Yangwarak Rural Municipality", nameNp: "पाथीभरा याङवरक गाउँपालिका", type: "rural", wards: 6 },
          { name: "Phaktanglung Rural Municipality", nameNp: "फक्ताङलुङ गाउँपालिका", type: "rural", wards: 7 },
          { name: "Phungling Municipality", nameNp: "फुङलिङ नगरपालिका", type: "municipality", wards: 11 },
          { name: "Sidingwa Rural Municipality", nameNp: "सिदिङ्वा गाउँपालिका", type: "rural", wards: 7 },
          { name: "Sirijangha Rural Municipality", nameNp: "सिरीजङ्घा गाउँपालिका", type: "rural", wards: 8 },
        ],
      },
      {
        name: "Terhathum",
        nameNp: "तेह्रथुम",
        municipalities: [
          { name: "Aathrai Rural Municipality", nameNp: "आठराई गाउँपालिका", type: "rural", wards: 7 },
          { name: "Chhathar Rural Municipality", nameNp: "छथर गाउँपालिका", type: "rural", wards: 6 },
          { name: "Laligurans Municipality", nameNp: "लालीगुराँस नगरपालिका", type: "municipality", wards: 9 },
          { name: "Menchayayem Rural Municipality", nameNp: "मेन्छयायेम गाउँपालिका", type: "rural", wards: 6 },
          { name: "Myanglung Municipality", nameNp: "म्याङलुङ नगरपालिका", type: "municipality", wards: 10 },
          { name: "Phedap Rural Municipality", nameNp: "फेदाप गाउँपालिका", type: "rural", wards: 5 },
        ],
      },
      {
        name: "Udayapur",
        nameNp: "उदयपुर",
        municipalities: [
          { name: "Belaka Municipality", nameNp: "वेलका नगरपालिका", type: "municipality", wards: 9 },
          { name: "Chaudandigadhi Municipality", nameNp: "चौदण्डीगढी नगरपालिका", type: "municipality", wards: 10 },
          { name: "Katari Municipality", nameNp: "कटारी नगरपालिका", type: "municipality", wards: 14 },
          { name: "Limchungbung Rural Municipality", nameNp: "लिम्चुङ्बुङ गाउँपालिका", type: "rural", wards: 5 },
          { name: "Rautamai Rural Municipality", nameNp: "रौतामाई गाउँपालिका", type: "rural", wards: 8 },
          { name: "Tapli Rural Municipality", nameNp: "ताप्ली गाउँपालिका", type: "rural", wards: 5 },
          { name: "Triyuga Municipality", nameNp: "त्रियुगा नगरपालिका", type: "municipality", wards: 16 },
          { name: "Udayapurgadhi Rural Municipality", nameNp: "उदयपुरगढी गाउँपालिका", type: "rural", wards: 8 },
        ],
      },
    ],
  },
  {
    name: "Madhesh",
    nameNp: "मधेश",
    districts: [
      {
        name: "Bara",
        nameNp: "बारा",
        municipalities: [
          { name: "Adarsh Kotwal Rural Municipality", nameNp: "आदर्श कोटवाल गाउँपालिका", type: "rural", wards: 8 },
          { name: "Baragadhi Rural Municipality", nameNp: "बारागढी गाउँपालिका", type: "rural", wards: 6 },
          { name: "Bishrampur Rural Municipality", nameNp: "विश्रामपुर गाउँपालिका", type: "rural", wards: 5 },
          { name: "Devtal Rural Municipality", nameNp: "देवताल गाउँपालिका", type: "rural", wards: 7 },
          { name: "Jitpur Simara Sub-Metropolitan City", nameNp: "जीतपुर सिमरा उपमहानगरपालिका", type: "sub_metropolitan", wards: 24 },
          { name: "Kalaiya Sub-Metropolitan City", nameNp: "कलैया उपमहानगरपालिका", type: "sub_metropolitan", wards: 27 },
          { name: "Karaiyamai Rural Municipality", nameNp: "करैयामाई गाउँपालिका", type: "rural", wards: 8 },
          { name: "Kolhabi Municipality", nameNp: "कोल्हवी नगरपालिका", type: "municipality", wards: 11 },
          { name: "Mahagadhimai Municipality", nameNp: "महागढीमाई नगरपालिका", type: "municipality", wards: 11 },
          { name: "Nijgadh Municipality", nameNp: "निजगढ नगरपालिका", type: "municipality", wards: 13 },
          { name: "Pacharauta Municipality", nameNp: "पचरौता नगरपालिका", type: "municipality", wards: 9 },
          { name: "Parwanipur Rural Municipality", nameNp: "परवानीपुर गाउँपालिका", type: "rural", wards: 5 },
          { name: "Pheta Rural Municipality", nameNp: "फेटा गाउँपालिका", type: "rural", wards: 7 },
          { name: "Prasauni Rural Municipality", nameNp: "प्रसौनी गाउँपालिका", type: "rural", wards: 7 },
          { name: "Simaraungadh Municipality", nameNp: "सिम्रौनगढ नगरपालिका", type: "municipality", wards: 11 },
          { name: "Suwarna Rural Municipality", nameNp: "सुवर्ण गाउँपालिका", type: "rural", wards: 8 },
        ],
      },
      {
        name: "Dhanusha",
        nameNp: "धनुषा",
        municipalities: [
          { name: "Aaurahi Rural Municipality", nameNp: "औरही गाउँपालिका", type: "rural", wards: 6 },
          { name: "Bateshwar Rural Municipality", nameNp: "बटेश्वर गाउँपालिका", type: "rural", wards: 5 },
          { name: "Bideha Municipality", nameNp: "विदेह नगरपालिका", type: "municipality", wards: 9 },
          { name: "Chhireshwarnath Municipality", nameNp: "क्षिरेश्वरनाथ नगरपालिका", type: "municipality", wards: 10 },
          { name: "Dhanauji Rural Municipality", nameNp: "धनौजी गाउँपालिका", type: "rural", wards: 5 },
          { name: "Dhanushadham Municipality", nameNp: "धनुषाधाम नगरपालिका", type: "municipality", wards: 9 },
          { name: "Ganeshman Charnath Municipality", nameNp: "गणेशमान चारनाथ नगरपालिका", type: "municipality", wards: 11 },
          { name: "Hansapur Municipality", nameNp: "हंसपुर नगरपालिका", type: "municipality", wards: 9 },
          { name: "Janaknandani Rural Municipality", nameNp: "जनकनन्दिनी गाउँपालिका", type: "rural", wards: 6 },
          { name: "Janakpurdham Sub-Metropolitan City", nameNp: "जनकपुरधाम उपमहानगरपालिका", type: "sub_metropolitan", wards: 25 },
          { name: "Kamala Municipality", nameNp: "कमला नगरपालिका", type: "municipality", wards: 9 },
          { name: "Lakshminya Rural Municipality", nameNp: "लक्ष्मीनिया गाउँपालिका", type: "rural", wards: 7 },
          { name: "Mithila Municipality", nameNp: "मिथिला नगरपालिका", type: "municipality", wards: 11 },
          { name: "MithilaBihari Municipality", nameNp: "मिथिला बिहारी नगरपालिका", type: "municipality", wards: 10 },
          { name: "Mukhiyapatti Musharniya Rural Municipality", nameNp: "मुखियापट्टी मुसहरमिया गाउँपालिका", type: "rural", wards: 6 },
          { name: "Nagarain Municipality", nameNp: "नगराइन नगरपालिका", type: "municipality", wards: 9 },
          { name: "Sabaila Municipality", nameNp: "सबैला नगरपालिका", type: "municipality", wards: 13 },
          { name: "Sahidnagar Municipality", nameNp: "शहीदनगर नगरपालिका", type: "municipality", wards: 9 },
        ],
      },
      {
        name: "Mahottari",
        nameNp: "महोत्तरी",
        municipalities: [
          { name: "Aaurahi Municipality", nameNp: "औरही नगरपालिका", type: "municipality", wards: 9 },
          { name: "Balawa Municipality", nameNp: "बलवा नगरपालिका", type: "municipality", wards: 11 },
          { name: "Bardibas Municipality", nameNp: "बर्दिबास नगरपालिका", type: "municipality", wards: 14 },
          { name: "Bhangaha Municipality", nameNp: "भँगाहा नगरपालिका", type: "municipality", wards: 9 },
          { name: "Ekdara Rural Municipality", nameNp: "एकडारा गाउँपालिका", type: "rural", wards: 6 },
          { name: "Gaushala Municipality", nameNp: "गौशाला नगरपालिका", type: "municipality", wards: 12 },
          { name: "Jaleshor Municipality", nameNp: "जलेश्वर नगरपालिका", type: "municipality", wards: 12 },
          { name: "Loharpatti Municipality", nameNp: "लोहरपट्टी नगरपालिका", type: "municipality", wards: 9 },
          { name: "Mahottari Rural Municipality", nameNp: "महोत्तरी गाउँपालिका", type: "rural", wards: 6 },
          { name: "Manara Shiswa Municipality", nameNp: "मनरा शिसवा नगरपालिका", type: "municipality", wards: 10 },
          { name: "Matihani Municipality", nameNp: "मटिहानी नगरपालिका", type: "municipality", wards: 9 },
          { name: "Pipara Rural Municipality", nameNp: "पिपरा गाउँपालिका", type: "rural", wards: 7 },
          { name: "Ramgopalpur Municipality", nameNp: "रामगोपालपुर नगरपालिका", type: "municipality", wards: 9 },
          { name: "Samsi Rural Municipality", nameNp: "साम्सी गाउँपालिका", type: "rural", wards: 7 },
          { name: "Sonama Rural Municipality", nameNp: "सोनमा गाउँपालिका", type: "rural", wards: 8 },
        ],
      },
      {
        name: "Parsa",
        nameNp: "पर्सा",
        municipalities: [
          { name: "Bahudarmai Municipality", nameNp: "बहुदरमाई नगरपालिका", type: "municipality", wards: 9 },
          { name: "Bindabasini Rural Municipality", nameNp: "बिन्दबासिनी गाउँपालिका", type: "rural", wards: 5 },
          { name: "Birgunj Metropolitan City", nameNp: "बिरगंज महानगरपालिका", type: "metropolitan", wards: 32 },
          { name: "Chhipaharmai Rural Municipality", nameNp: "छिपहरमाई गाउँपालिका", type: "rural", wards: 5 },
          { name: "Dhobini Rural Municipality", nameNp: "धोबीनी गाउँपालिका", type: "rural", wards: 5 },
          { name: "Jagarnathpur Rural Municipality", nameNp: "जगरनाथपुर गाउँपालिका", type: "rural", wards: 6 },
          { name: "Jirabhawani Rural Municipality", nameNp: "जिरा भवानी गाउँपालिका", type: "rural", wards: 5 },
          { name: "Kalikamai Rural Municipality", nameNp: "कालिकामाई गाउँपालिका", type: "rural", wards: 5 },
          { name: "Pakaha Mainpur Rural Municipality", nameNp: "पकाहा मैनपुर गाउँपालिका", type: "rural", wards: 5 },
          { name: "Parsagadhi Municipality", nameNp: "पर्सागढी नगरपालिका", type: "municipality", wards: 9 },
          { name: "Paterwa Sugauli Rural Municipality", nameNp: "पटेर्वा सुगौली गाउँपालिका", type: "rural", wards: 5 },
          { name: "Pokhariya Municipality", nameNp: "पोखरिया नगरपालिका", type: "municipality", wards: 10 },
          { name: "Sakhuwa Prasauni Rural Municipality", nameNp: "सखुवा प्रसौनी गाउँपालिका", type: "rural", wards: 6 },
          { name: "Thori Rural Municipality", nameNp: "ठोरी गाउँपालिका", type: "rural", wards: 5 },
        ],
      },
      {
        name: "Rautahat",
        nameNp: "रौतहट",
        municipalities: [
          { name: "Baudhimai Municipality", nameNp: "बौधीमाई नगरपालिका", type: "municipality", wards: 9 },
          { name: "Brindaban Municipality", nameNp: "बृन्दावन नगरपालिका", type: "municipality", wards: 9 },
          { name: "Chandrapur Municipality", nameNp: "चन्द्रपुर नगरपालिका", type: "municipality", wards: 10 },
          { name: "Dewahi Gonahi Municipality", nameNp: "देवाही गोनाही नगरपालिका", type: "municipality", wards: 9 },
          { name: "Durga Bhagwati Rural Municipality", nameNp: "दुर्गा भगवती गाउँपालिका", type: "rural", wards: 5 },
          { name: "Gadhimai Municipality", nameNp: "गढीमाई नगरपालिका", type: "municipality", wards: 9 },
          { name: "Gaur Municipality", nameNp: "गौर नगरपालिका", type: "municipality", wards: 9 },
          { name: "Gujara Municipality", nameNp: "गुजरा नगरपालिका", type: "municipality", wards: 9 },
          { name: "Guruda Municipality", nameNp: "गरुडा नगरपालिका", type: "municipality", wards: 9 },
          { name: "Ishanath Municipality", nameNp: "ईशनाथ नगरपालिका", type: "municipality", wards: 9 },
          { name: "Katahariya Municipality", nameNp: "कटहरिया नगरपालिका", type: "municipality", wards: 9 },
          { name: "Madhav Narayan Municipality", nameNp: "माधव नारायण नगरपालिका", type: "municipality", wards: 9 },
          { name: "Maulapur Municipality", nameNp: "मौलापुर नगरपालिका", type: "municipality", wards: 9 },
          { name: "Paroha Municipality", nameNp: "परोहा नगरपालिका", type: "municipality", wards: 9 },
          { name: "Phatuwa Bijayapur Municipality", nameNp: "फतुवाबिजयपुर नगरपालिका", type: "municipality", wards: 11 },
          { name: "Rajdevi Municipality", nameNp: "राजदेवी नगरपालिका", type: "municipality", wards: 9 },
          { name: "Rajpur Municipality", nameNp: "राजपुर नगरपालिका", type: "municipality", wards: 9 },
          { name: "Yamunamai Rural Municipality", nameNp: "यमुनामाई गाउँपालिका", type: "rural", wards: 5 },
        ],
      },
      {
        name: "Saptari",
        nameNp: "सप्तरी",
        municipalities: [
          { name: "Agnisaira Krishnasavaran Rural Municipality", nameNp: "अग्निसाइर कृष्णासरवन गाउँपालिका", type: "rural", wards: 6 },
          { name: "Balan-Bihul Rural Municipality", nameNp: "बलान-बिहुल गाउँपालिका", type: "rural", wards: 6 },
          { name: "Bishnupur Rural Municipality", nameNp: "बिष्णुपुर गाउँपालिका", type: "rural", wards: 7 },
          { name: "Bodebarsain Municipality", nameNp: "बोदेबरसाईन नगरपालिका", type: "municipality", wards: 10 },
          { name: "Chhinnamasta Rural Municipality", nameNp: "छिन्नमस्ता गाउँपालिका", type: "rural", wards: 7 },
          { name: "Dakneshwori Municipality", nameNp: "डाक्नेश्वरी नगरपालिका", type: "municipality", wards: 10 },
          { name: "Hanumannagar Kankalini Municipality", nameNp: "हनुमाननगर कङ्‌कालिनी नगरपालिका", type: "municipality", wards: 14 },
          { name: "Kanchanrup Municipality", nameNp: "कञ्चनरुप नगरपालिका", type: "municipality", wards: 12 },
          { name: "Khadak Municipality", nameNp: "खडक नगरपालिका", type: "municipality", wards: 11 },
          { name: "Mahadeva Rural Municipality", nameNp: "महादेवा गाउँपालिका", type: "rural", wards: 6 },
          { name: "Rajbiraj Municipality", nameNp: "राजविराज नगरपालिका", type: "municipality", wards: 16 },
          { name: "Rajgadh Rural Municipality", nameNp: "राजगढ गाउँपालिका", type: "rural", wards: 6 },
          { name: "Rupani Rural Municipality", nameNp: "रुपनी गाउँपालिका", type: "rural", wards: 6 },
          { name: "Saptakoshi Municipality", nameNp: "सप्तकोशी नगरपालिका", type: "municipality", wards: 11 },
          { name: "Shambhunath Municipality", nameNp: "शम्भुनाथ नगरपालिका", type: "municipality", wards: 12 },
          { name: "Surunga Municipality", nameNp: "सुरुङ्‍गा नगरपालिका", type: "municipality", wards: 11 },
          { name: "Tilathi Koiladi Rural Municipality", nameNp: "तिलाठी कोईलाडी गाउँपालिका", type: "rural", wards: 8 },
          { name: "Tirhut Rural Municipality", nameNp: "तिरहुत गाउँपालिका", type: "rural", wards: 5 },
        ],
      },
      {
        name: "Sarlahi",
        nameNp: "सर्लाही",
        municipalities: [
          { name: "Bagmati Municipality", nameNp: "बागमती नगरपालिका", type: "municipality", wards: 12 },
          { name: "Balara Municipality", nameNp: "बलरा नगरपालिका", type: "municipality", wards: 11 },
          { name: "Barahathwa Municipality", nameNp: "बरहथवा नगरपालिका", type: "municipality", wards: 18 },
          { name: "Basbariya Rural Municipality", nameNp: "बसबरीया गाउँपालिका", type: "rural", wards: 6 },
          { name: "Bisnu Rural Municipality", nameNp: "विष्णु गाउँपालिका", type: "rural", wards: 8 },
          { name: "Brahampuri Rural Municipality", nameNp: "ब्रह्मपुरी गाउँपालिका", type: "rural", wards: 7 },
          { name: "Chakraghatta Rural Municipality", nameNp: "चक्रघट्टा गाउँपालिका", type: "rural", wards: 9 },
          { name: "Chandranagar Rural Municipality", nameNp: "चन्द्रनगर गाउँपालिका", type: "rural", wards: 7 },
          { name: "Dhankaul Rural Municipality", nameNp: "धनकौल गाउँपालिका", type: "rural", wards: 7 },
          { name: "Godaita Municipality", nameNp: "गोडैटा नगरपालिका", type: "municipality", wards: 12 },
          { name: "Haripur Municipality", nameNp: "हरिपुर नगरपालिका", type: "municipality", wards: 9 },
          { name: "Haripurwa Municipality", nameNp: "हरिपुर्वा नगरपालिका", type: "municipality", wards: 9 },
          { name: "Hariwan Municipality", nameNp: "हरिवन नगरपालिका", type: "municipality", wards: 11 },
          { name: "Ishowrpur Municipality", nameNp: "ईश्वरपुर नगरपालिका", type: "municipality", wards: 15 },
          { name: "Kabilasi Municipality", nameNp: "कविलासी नगरपालिका", type: "municipality", wards: 10 },
          { name: "Kaudena Rural Municipality", nameNp: "कौडेना गाउँपालिका", type: "rural", wards: 7 },
          { name: "Lalbandi Municipality", nameNp: "लालबन्दी नगरपालिका", type: "municipality", wards: 17 },
          { name: "Malangawa Municipality", nameNp: "मलंगवा नगरपालिका", type: "municipality", wards: 12 },
          { name: "Parsa Rural Municipality", nameNp: "पर्सा गाउँपालिका", type: "rural", wards: 6 },
          { name: "Ramnagar Rural Municipality", nameNp: "रामनगर गाउँपालिका", type: "rural", wards: 7 },
        ],
      },
      {
        name: "Siraha",
        nameNp: "सिराहा",
        municipalities: [
          { name: "Arnama Rural Municipality", nameNp: "अर्नमा गाउँपालिका", type: "rural", wards: 5 },
          { name: "Aurahi Rural Municipality", nameNp: "औरही गाउँपालिका", type: "rural", wards: 5 },
          { name: "Bariyarpatti Rural Municipality", nameNp: "बरियारपट्टी गाउँपालिका", type: "rural", wards: 5 },
          { name: "Bhagwanpur Rural Municipality", nameNp: "भगवानपुर गाउँपालिका", type: "rural", wards: 5 },
          { name: "Bishnupur Rural Municipality", nameNp: "विष्णुपुर गाउँपालिका", type: "rural", wards: 5 },
          { name: "Dhangadhimai Municipality", nameNp: "धनगढीमाई नगरपालिका", type: "municipality", wards: 14 },
          { name: "Golbazar Municipality", nameNp: "गोलबजार नगरपालिका", type: "municipality", wards: 13 },
          { name: "Kalyanpur Municipality", nameNp: "कल्याणपुर नगरपालिका", type: "municipality", wards: 12 },
          { name: "Karjanha Municipality", nameNp: "कर्जन्हा नगरपालिका", type: "municipality", wards: 11 },
          { name: "Lahan Municipality", nameNp: "लहान नगरपालिका", type: "municipality", wards: 24 },
          { name: "Lakshmipur Patari Rural Municipality", nameNp: "लक्ष्मीपुर पतारी गाउँपालिका", type: "rural", wards: 6 },
          { name: "Mirchaiya Municipality", nameNp: "मिर्चैयाँ नगरपालिका", type: "municipality", wards: 12 },
          { name: "Naraha Rural Municipality", nameNp: "नरहा गाउँपालिका", type: "rural", wards: 5 },
          { name: "Navarajpur Rural Municipality", nameNp: "नवराजपुर गाउँपालिका", type: "rural", wards: 5 },
          { name: "SakhuwanankarKatti Rural Municipality", nameNp: "सखुवानान्कारकट्टी गाउँपालिका", type: "rural", wards: 5 },
          { name: "Siraha Municipality", nameNp: "सिरहा नगरपालिका", type: "municipality", wards: 22 },
          { name: "Sukhipur Municipality", nameNp: "सुखीपुर नगरपालिका", type: "municipality", wards: 10 },
        ],
      },
    ],
  },
  {
    name: "Bagmati",
    nameNp: "बाग्मती",
    districts: [
      {
        name: "Bhaktapur",
        nameNp: "भक्तपुर",
        municipalities: [
          { name: "Bhaktapur Municipality", nameNp: "भक्तपुर नगरपालिका", type: "municipality", wards: 10 },
          { name: "Changunarayan Municipality", nameNp: "चाँगुनारायण नगरपालिका", type: "municipality", wards: 9 },
          { name: "Madhyapur Thimi Municipality", nameNp: "मध्यपुर थिमी नगरपालिका", type: "municipality", wards: 9 },
          { name: "Suryabinayak Municipality", nameNp: "सूर्यविनायक नगरपालिका", type: "municipality", wards: 10 },
        ],
      },
      {
        name: "Chitwan",
        nameNp: "चितवन",
        municipalities: [
          { name: "Bharatpur Metropolitan City", nameNp: "भरतपुर महानगरपालिका", type: "metropolitan", wards: 29 },
          { name: "Ichchhakamana Rural Municipality", nameNp: "इच्छाकामना गाउँपालिका", type: "rural", wards: 7 },
          { name: "Kalika Municipality", nameNp: "कालिका नगरपालिका", type: "municipality", wards: 11 },
          { name: "Khairhani Municipality", nameNp: "खैरहनी नगरपालिका", type: "municipality", wards: 13 },
          { name: "Madi Municipality", nameNp: "माडी नगरपालिका", type: "municipality", wards: 9 },
          { name: "Rapti Municipality", nameNp: "राप्ती नगरपालिका", type: "municipality", wards: 13 },
          { name: "Ratnagar Municipality", nameNp: "रत्ननगर नगरपालिका", type: "municipality", wards: 16 },
        ],
      },
      {
        name: "Dhading",
        nameNp: "धादिंङ्ग",
        municipalities: [
          { name: "Benighat Rorang Rural Municipality", nameNp: "बेनीघाट रोराङ्ग गाउँपालिका", type: "rural", wards: 10 },
          { name: "Dhunibeshi Municipality", nameNp: "धुनीबेंशी नगरपालिका", type: "municipality", wards: 9 },
          { name: "Gajuri Rural Municipality", nameNp: "गजुरी गाउँपालिका", type: "rural", wards: 8 },
          { name: "Galchhi Rural Municipality", nameNp: "गल्छी गाउँपालिका", type: "rural", wards: 8 },
          { name: "Gangajamuna Rural Municipality", nameNp: "गङ्गाजमुना गाउँपालिका", type: "rural", wards: 7 },
          { name: "Jwalamukhi Rural Municipality", nameNp: "ज्वालामूखी गाउँपालिका", type: "rural", wards: 7 },
          { name: "Khaniyabas Rural Municipality", nameNp: "खनियाबास गाउँपालिका", type: "rural", wards: 5 },
          { name: "Netrawati Dabjong Rural Municipality", nameNp: "नेत्रावती डबजोङ गाउँपालिका", type: "rural", wards: 5 },
          { name: "Nilkantha Municipality", nameNp: "निलकण्ठ नगरपालिका", type: "municipality", wards: 14 },
          { name: "Rubi Valley Rural Municipality", nameNp: "रुवी भ्याली गाउँपालिका", type: "rural", wards: 6 },
          { name: "Siddhalek Rural Municipality", nameNp: "सिद्धलेक गाउँपालिका", type: "rural", wards: 7 },
          { name: "Thakre Rural Municipality", nameNp: "थाक्रे गाउँपालिका", type: "rural", wards: 11 },
          { name: "Tripurasundari Rural Municipality", nameNp: "त्रिपुरासुन्दरी गाउँपालिका", type: "rural", wards: 7 },
        ],
      },
      {
        name: "Dolakha",
        nameNp: "दोलखा",
        municipalities: [
          { name: "Baiteshowr Rural Municipality", nameNp: "वैतेश्वर गाउँपालिका", type: "rural", wards: 8 },
          { name: "Bhimeswor Municipality", nameNp: "भिमेश्वर नगरपालिका", type: "municipality", wards: 9 },
          { name: "Bigu Rural Municipality", nameNp: "विगु गाउँपालिका", type: "rural", wards: 8 },
          { name: "Gaurishankar Rural Municipality", nameNp: "गौरीशङ्कर गाउँपालिका", type: "rural", wards: 9 },
          { name: "Jiri Municipality", nameNp: "जिरी नगरपालिका", type: "municipality", wards: 9 },
          { name: "Kalinchok Rural Municipality", nameNp: "कालिन्चोक गाउँपालिका", type: "rural", wards: 9 },
          { name: "Melung Rural Municipality", nameNp: "मेलुङ्ग गाउँपालिका", type: "rural", wards: 7 },
          { name: "Sailung Rural Municipality", nameNp: "शैलुङ्ग गाउँपालिका", type: "rural", wards: 8 },
          { name: "Tamakoshi Rural Municipality", nameNp: "तामाकोशी गाउँपालिका", type: "rural", wards: 7 },
        ],
      },
      {
        name: "Kathmandu",
        nameNp: "काठमाडौँ",
        municipalities: [
          { name: "Budhanilkantha Municipality", nameNp: "बुढानिलकण्ठ नगरपालिका", type: "municipality", wards: 13 },
          { name: "Chandragiri Municipality", nameNp: "चन्द्रागिरी नगरपालिका", type: "municipality", wards: 15 },
          { name: "Dakshinkali Municipality", nameNp: "दक्षिणकाली नगरपालिका", type: "municipality", wards: 9 },
          { name: "Gokarneshwar Municipality", nameNp: "गोकर्णेश्वर नगरपालिका", type: "municipality", wards: 9 },
          { name: "Kageshwari-Manohara Municipality", nameNp: "कागेश्वरी मनोहरा नगरपालिका", type: "municipality", wards: 9 },
          { name: "Kathmandu Metropolitan City", nameNp: "काठमाण्डौं महानगरपालिका", type: "metropolitan", wards: 32 },
          { name: "Kirtipur Municipality", nameNp: "कीर्तिपुर नगरपालिका", type: "municipality", wards: 10 },
          { name: "Nagarjun Municipality", nameNp: "नागार्जुन नगरपालिका", type: "municipality", wards: 10 },
          { name: "Shankharapur Municipality", nameNp: "शङ्खरापुर नगरपालिका", type: "municipality", wards: 9 },
          { name: "Tarakeshwar Municipality", nameNp: "तारकेश्वर नगरपालिका", type: "municipality", wards: 11 },
          { name: "Tokha Municipality", nameNp: "टोखा नगरपालिका", type: "municipality", wards: 11 },
        ],
      },
      {
        name: "Kavrepalanchok",
        nameNp: "काभ्रेपलान्चोक",
        municipalities: [
          { name: "Banepa Municipality", nameNp: "बनेपा नगरपालिका", type: "municipality", wards: 14 },
          { name: "Bethanchok Rural Municipality", nameNp: "बेथानचोक गाउँपालिका", type: "rural", wards: 6 },
          { name: "Bhumlu Rural Municipality", nameNp: "भुम्लु गाउँपालिका", type: "rural", wards: 10 },
          { name: "Chauri Deurali Rural Municipality", nameNp: "चौंरीदेउराली गाउँपालिका", type: "rural", wards: 9 },
          { name: "Dhulikhel Municipality", nameNp: "धुलिखेल नगरपालिका", type: "municipality", wards: 12 },
          { name: "Khani Khola Rural Municipality", nameNp: "खानीखोला गाउँपालिका", type: "rural", wards: 7 },
          { name: "Mahabharat Rural Municipality", nameNp: "महाभारत गाउँपालिका", type: "rural", wards: 8 },
          { name: "Mandandeupur Municipality", nameNp: "मण्डनदेउपुर नगरपालिका", type: "municipality", wards: 12 },
          { name: "Namobuddha Municipality", nameNp: "नमोबुद्ध नगरपालिका", type: "municipality", wards: 11 },
          { name: "Panauti Municipality", nameNp: "पनौती नगरपालिका", type: "municipality", wards: 12 },
          { name: "Panchkhal Municipality", nameNp: "पाँचखाल नगरपालिका", type: "municipality", wards: 13 },
          { name: "Roshi Rural Municipality", nameNp: "रोशी गाउँपालिका", type: "rural", wards: 12 },
          { name: "Temal Rural Municipality", nameNp: "तेमाल गाउँपालिका", type: "rural", wards: 9 },
        ],
      },
      {
        name: "Lalitpur",
        nameNp: "ललितपुर",
        municipalities: [
          { name: "Bagmati Rural Municipality", nameNp: "बागमती गाउँपालिका", type: "rural", wards: 7 },
          { name: "Godawari Municipality", nameNp: "गोदावरी नगरपालिका", type: "municipality", wards: 14 },
          { name: "Konjyosom Rural Municipality", nameNp: "कोन्ज्योसोम गाउँपालिका", type: "rural", wards: 5 },
          { name: "Lalitpur Metropolitan City", nameNp: "ललितपुर महानगरपालिका", type: "metropolitan", wards: 29 },
          { name: "Mahalaxmi Municipality", nameNp: "महालक्ष्मी नगरपालिका", type: "municipality", wards: 10 },
          { name: "Mahankal Rural Municipality", nameNp: "महाङ्काल गाउँपालिका", type: "rural", wards: 6 },
        ],
      },
      {
        name: "Makwanpur",
        nameNp: "मकवानपुर",
        municipalities: [
          { name: "Bagmati Rural Municipality", nameNp: "बाग्मति गाउँपालिका", type: "rural", wards: 9 },
          { name: "Bakaiya Rural Municipality", nameNp: "बकैया गाउँपालिका", type: "rural", wards: 12 },
          { name: "Bhimphedi Rural Municipality", nameNp: "भिमफेदी गाउँपालिका", type: "rural", wards: 9 },
          { name: "Hetauda Sub-Metropolitan City", nameNp: "हेटौडा उपमहानगरपालिका", type: "sub_metropolitan", wards: 19 },
          { name: "Indrasarowar Rural Municipality", nameNp: "इन्द्रसरोबर गाउँपालिका", type: "rural", wards: 5 },
          { name: "Kailash Rural Municipality", nameNp: "कैलाश गाउँपालिका", type: "rural", wards: 10 },
          { name: "Makawanpurgadhi Rural Municipality", nameNp: "मकवानपुरगढी गाउँपालिका", type: "rural", wards: 8 },
          { name: "Manahari Rural Municipality", nameNp: "मनहरी गाउँपालिका", type: "rural", wards: 9 },
          { name: "Raksirang Rural Municipality", nameNp: "राक्सिराङ्ग गाउँपालिका", type: "rural", wards: 9 },
          { name: "Thaha Municipality", nameNp: "थाहा नगरपालिका", type: "municipality", wards: 12 },
        ],
      },
      {
        name: "Nuwakot",
        nameNp: "नुवाकोट",
        municipalities: [
          { name: "Belkotgadhi Municipality", nameNp: "बेलकोटगढी नगरपालिका", type: "municipality", wards: 13 },
          { name: "Bidur Municipality", nameNp: "विदुर नगरपालिका", type: "municipality", wards: 13 },
          { name: "Dupcheshwar Rural Municipality", nameNp: "दुप्चेश्वर गाउँपालिका", type: "rural", wards: 7 },
          { name: "Kakani Rural Municipality", nameNp: "ककनी गाउँपालिका", type: "rural", wards: 8 },
          { name: "Kispang Rural Municipality", nameNp: "किस्पाङ गाउँपालिका", type: "rural", wards: 5 },
          { name: "Likhu Rural Municipality", nameNp: "लिखु गाउँपालिका", type: "rural", wards: 6 },
          { name: "Myagang Rural Municipality", nameNp: "म्यगङ गाउँपालिका", type: "rural", wards: 6 },
          { name: "Panchakanya Rural Municipality", nameNp: "पञ्चकन्या गाउँपालिका", type: "rural", wards: 5 },
          { name: "Shivapuri Rural Municipality", nameNp: "शिवपुरी गाउँपालिका", type: "rural", wards: 8 },
          { name: "Suryagadhi Rural Municipality", nameNp: "सुर्यगढी गाउँपालिका", type: "rural", wards: 5 },
          { name: "Tadi Rural Municipality", nameNp: "तादी गाउँपालिका", type: "rural", wards: 6 },
          { name: "Tarkeshwar Rural Municipality", nameNp: "तारकेश्वर गाउँपालिका", type: "rural", wards: 6 },
        ],
      },
      {
        name: "Ramechap",
        nameNp: "रामेछाप",
        municipalities: [
          { name: "Doramba Rural Municipality", nameNp: "दोरम्बा गाउँपालिका", type: "rural", wards: 7 },
          { name: "Gokulganga Rural Municipality", nameNp: "गोकुलगङ्गा गाउँपालिका", type: "rural", wards: 6 },
          { name: "Khandadevi Rural Municipality", nameNp: "खाँडादेवी गाउँपालिका", type: "rural", wards: 9 },
          { name: "LikhuTamakoshi Rural Municipality", nameNp: "लिखु तामाकोशी गाउँपालिका", type: "rural", wards: 7 },
          { name: "Manthali Municipality", nameNp: "मन्थली नगरपालिका", type: "municipality", wards: 14 },
          { name: "Ramechhap Municipality", nameNp: "रामेछाप नगरपालिका", type: "municipality", wards: 9 },
          { name: "Sunapati Rural Municipality", nameNp: "सुनापती गाउँपालिका", type: "rural", wards: 5 },
          { name: "Umakunda Rural Municipality", nameNp: "उमाकुण्ड गाउँपालिका", type: "rural", wards: 7 },
        ],
      },
      {
        name: "Rasuwa",
        nameNp: "रसुवा",
        municipalities: [
          { name: "Gosaikunda Rural Municipality", nameNp: "गोसाईकुण्ड गाउँपालिका", type: "rural", wards: 6 },
          { name: "Kalika Rural Municipality", nameNp: "कालिका गाउँपालिका", type: "rural", wards: 5 },
          { name: "Naukunda Rural Municipality", nameNp: "नौकुण्ड गाउँपालिका", type: "rural", wards: 6 },
          { name: "Parbatikunda Rural Municipality", nameNp: "आमाछोदिङमो गाउँपालिका", type: "rural", wards: 5 },
          { name: "Uttargaya Rural Municipality", nameNp: "उत्तरगया गाउँपालिका", type: "rural", wards: 5 },
        ],
      },
      {
        name: "Sindhuli",
        nameNp: "सिन्धुली",
        municipalities: [
          { name: "Dudhauli Municipality", nameNp: "दुधौली नगरपालिका", type: "municipality", wards: 14 },
          { name: "Ghyanglekh Rural Municipality", nameNp: "घ्याङलेख गाउँपालिका", type: "rural", wards: 5 },
          { name: "Golanjor Rural Municipality", nameNp: "गोलन्जर गाउँपालिका", type: "rural", wards: 7 },
          { name: "Hariharpurgadhi Rural Municipality", nameNp: "हरिहरपुरगढी गाउँपालिका", type: "rural", wards: 8 },
          { name: "Kamalamai Municipality", nameNp: "कमलामाई नगरपालिका", type: "municipality", wards: 14 },
          { name: "Marin Rural Municipality", nameNp: "मरिण गाउँपालिका", type: "rural", wards: 7 },
          { name: "Phikkal Rural Municipality", nameNp: "फिक्कल गाउँपालिका", type: "rural", wards: 6 },
          { name: "Sunkoshi Rural Municipality", nameNp: "सुनकोशी गाउँपालिका", type: "rural", wards: 7 },
          { name: "Tinpatan Rural Municipality", nameNp: "तीनपाटन गाउँपालिका", type: "rural", wards: 11 },
        ],
      },
      {
        name: "Sindhupalchok",
        nameNp: "सिन्धुपाल्चोक",
        municipalities: [
          { name: "Bahrabise Municipality", nameNp: "बाह्रविसे नगरपालिका", type: "municipality", wards: 9 },
          { name: "Balephi Rural Municipality", nameNp: "बलेफी गाउँपालिका", type: "rural", wards: 8 },
          { name: "Bhotekoshi Rural Municipality", nameNp: "भोटेकोशी गाउँपालिका", type: "rural", wards: 5 },
          { name: "Chautara Sangachowkgadi Municipality", nameNp: "चौतारा साँगाचोकगढी नगरपालिका", type: "municipality", wards: 14 },
          { name: "Helambu Rural Municipality", nameNp: "हेलम्बु गाउँपालिका", type: "rural", wards: 7 },
          { name: "Indrawati Rural Municipality", nameNp: "ईन्द्रावती गाउँपालिका", type: "rural", wards: 12 },
          { name: "Jugal Rural Municipality", nameNp: "जुगल गाउँपालिका", type: "rural", wards: 7 },
          { name: "Lisankhu Rural Municipality", nameNp: "लिसङ्खु पाखर गाउँपालिका", type: "rural", wards: 7 },
          { name: "Melamchi Municipality", nameNp: "मेलम्ची नगरपालिका", type: "municipality", wards: 13 },
          { name: "Panchpokhari Rural Municipality", nameNp: "पाँचपोखरी थाङपाल गाउँपालिका", type: "rural", wards: 8 },
          { name: "Sunkoshi Rural Municipality", nameNp: "सुनकोशी गाउँपालिका", type: "rural", wards: 7 },
          { name: "Tripurasundari Rural Municipality", nameNp: "त्रिपुरासुन्दरी गाउँपालिका", type: "rural", wards: 6 },
        ],
      },
    ],
  },
  {
    name: "Gandaki",
    nameNp: "गण्डकी",
    districts: [
      {
        name: "Baglung",
        nameNp: "बागलुङ",
        municipalities: [
          { name: "Badigad Rural Municipality", nameNp: "वडिगाड गाउँपालिका", type: "rural", wards: 10 },
          { name: "Baglung Municipality", nameNp: "बागलुङ नगरपालिका", type: "municipality", wards: 14 },
          { name: "Bareng Rural Municipality", nameNp: "वरेङ गाउँपालिका", type: "rural", wards: 5 },
          { name: "Dhorpatan Municipality", nameNp: "ढोरपाटन नगरपालिका", type: "municipality", wards: 9 },
          { name: "Galkot Municipality", nameNp: "गल्कोट नगरपालिका", type: "municipality", wards: 11 },
          { name: "Jaimuni Municipality", nameNp: "जैमूनी नगरपालिका", type: "municipality", wards: 10 },
          { name: "Khathekhola Rural Municipality", nameNp: "काठेखोला गाउँपालिका", type: "rural", wards: 8 },
          { name: "Nishi Khola Rural Municipality", nameNp: "निसीखोला गाउँपालिका", type: "rural", wards: 7 },
          { name: "Taman Khola Rural Municipality", nameNp: "तमानखोला गाउँपालिका", type: "rural", wards: 6 },
          { name: "Tara Khola Rural Municipality", nameNp: "ताराखोला गाउँपालिका", type: "rural", wards: 5 },
        ],
      },
      {
        name: "Gorkha",
        nameNp: "गोरखा",
        municipalities: [
          { name: "Aarughat Rural Municipality", nameNp: "आरूघाट गाउँपालिका", type: "rural", wards: 10 },
          { name: "Ajirkot Rural Municipality", nameNp: "अजिरकोट गाउँपालिका", type: "rural", wards: 5 },
          { name: "Bhimsen Thapa Rural Municipality", nameNp: "भिमसेनथापा गाउँपालिका", type: "rural", wards: 8 },
          { name: "Chumnubri Rural Municipality", nameNp: "चुमनुव्री गाउँपालिका", type: "rural", wards: 7 },
          { name: "Dharche Rural Municipality", nameNp: "धार्चे गाउँपालिका", type: "rural", wards: 7 },
          { name: "Gandaki Rural Municipality", nameNp: "गण्डकी गाउँपालिका", type: "rural", wards: 8 },
          { name: "Gorkha Municipality", nameNp: "गोरखा नगरपालिका", type: "municipality", wards: 14 },
          { name: "Palungtar Municipality", nameNp: "पालुङटार नगरपालिका", type: "municipality", wards: 10 },
          { name: "Sahid Lakhan Rural Municipality", nameNp: "शहिद लखन गाउँपालिका", type: "rural", wards: 9 },
          { name: "Siranchowk Rural Municipality", nameNp: "सिरानचोक गाउँपालिका", type: "rural", wards: 8 },
          { name: "Sulikot Rural Municipality", nameNp: "बारपाक सुलिकोट गाउँपालिका", type: "rural", wards: 8 },
        ],
      },
      {
        name: "Kaski",
        nameNp: "कास्की",
        municipalities: [
          { name: "Annapurna Rural Municipality", nameNp: "अन्नपूर्ण गाउँपालिका", type: "rural", wards: 11 },
          { name: "Machhapuchchhre Rural Municipality", nameNp: "माछापुच्छ्रे गाउँपालिका", type: "rural", wards: 9 },
          { name: "Madi Rural Municipality", nameNp: "मादी गाउँपालिका", type: "rural", wards: 12 },
          { name: "Pokhara Metropolitan City", nameNp: "पोखरा महानगरपालिका", type: "metropolitan", wards: 33 },
          { name: "Rupa Rural Municipality", nameNp: "रूपा गाउँपालिका", type: "rural", wards: 7 },
        ],
      },
      {
        name: "Lamjung",
        nameNp: "लमजुङ",
        municipalities: [
          { name: "Besisahar Municipality", nameNp: "बेसीशहर नगरपालिका", type: "municipality", wards: 11 },
          { name: "Dordi Rural Municipality", nameNp: "दोर्दी गाउँपालिका", type: "rural", wards: 9 },
          { name: "Dudhpokhari Rural Municipality", nameNp: "दूधपोखरी गाउँपालिका", type: "rural", wards: 6 },
          { name: "Kwhlosothar Rural Municipality", nameNp: "क्व्होलासोथार गाउँपालिका", type: "rural", wards: 9 },
          { name: "Madhya Nepal Municipality", nameNp: "मध्यनेपाल नगरपालिका", type: "municipality", wards: 10 },
          { name: "Marsyangdi Rural Municipality", nameNp: "मर्स्याङदी गाउँपालिका", type: "rural", wards: 9 },
          { name: "Rainas Municipality", nameNp: "रारइनास नगरपालिका", type: "municipality", wards: 10 },
          { name: "Sundarbazar Municipality", nameNp: "सुन्दरबजार नगरपालिका", type: "municipality", wards: 11 },
        ],
      },
      {
        name: "Manang",
        nameNp: "मनाङ",
        municipalities: [
          { name: "Chame Rural Municipality", nameNp: "चामे गाउँपालिका", type: "rural", wards: 5 },
          { name: "Manang Ngisyang Rural Municipality", nameNp: "मनाङ ङिस्याङ गाउँपालिका", type: "rural", wards: 9 },
          { name: "NarpaBhumi Rural Municipality", nameNp: "नार्पा भूमि गाउँपालिका", type: "rural", wards: 5 },
          { name: "Nason Rural Municipality", nameNp: "नासोँ गाउँपालिका", type: "rural", wards: 9 },
        ],
      },
      {
        name: "Mustang",
        nameNp: "मुस्ताङ",
        municipalities: [
          { name: "Barhagaun Muktichhetra Rural Municipality", nameNp: "वारागुङ मुक्तिक्षेत्र गाउँपालिका", type: "rural", wards: 5 },
          { name: "Gharpajhong Rural Municipality", nameNp: "घरपझोङ गाउँपालिका", type: "rural", wards: 5 },
          { name: "Lo-Ghekar Damodarkunda Rural Municipality", nameNp: "लो-घेकर दामोदरकुण्ड गाउँपालिका", type: "rural", wards: 5 },
          { name: "Lomanthang Rural Municipality", nameNp: "लोमन्थाङ गाउँपालिका", type: "rural", wards: 5 },
          { name: "Thasang Rural Municipality", nameNp: "थासाङ गाउँपालिका", type: "rural", wards: 5 },
        ],
      },
      {
        name: "Myagdi",
        nameNp: "म्याग्दी",
        municipalities: [
          { name: "Annapurna Rural Municipality", nameNp: "अन्नपुर्ण गाउँपालिका", type: "rural", wards: 8 },
          { name: "Beni Municipality", nameNp: "बेनी नगरपालिका", type: "municipality", wards: 10 },
          { name: "Dhaulagiri Rural Municipality", nameNp: "धवलागिरी गाउँपालिका", type: "rural", wards: 7 },
          { name: "Malika Rural Municipality", nameNp: "मालिका गाउँपालिका", type: "rural", wards: 7 },
          { name: "Mangala Rural Municipality", nameNp: "मंगला गाउँपालिका", type: "rural", wards: 5 },
          { name: "Raghuganga Rural Municipality", nameNp: "रघुगंगा गाउँपालिका", type: "rural", wards: 8 },
        ],
      },
      {
        name: "Nawalpur",
        nameNp: "नवलपुर",
        municipalities: [
          { name: "Baudikali Rural Municipality", nameNp: "बौदीकाली गाउँपालिका", type: "rural", wards: 6 },
          { name: "Binayi Tribeni Rural Municipality", nameNp: "विनयी त्रिवेणी गाउँपालिका", type: "rural", wards: 7 },
          { name: "Bulingtar Rural Municipality", nameNp: "बुलिङटार गाउँपालिका", type: "rural", wards: 6 },
          { name: "Devachuli Municipality", nameNp: "देवचुली नगरपालिका", type: "municipality", wards: 17 },
          { name: "Gaindakot Municipality", nameNp: "गैडाकोट नगरपालिका", type: "municipality", wards: 18 },
          { name: "Hupsekot Rural Municipality", nameNp: "हुप्सेकोट गाउँपालिका", type: "rural", wards: 6 },
          { name: "Kawasoti Municipality", nameNp: "कावासोती नगरपालिका", type: "municipality", wards: 17 },
          { name: "Madhya Bindu Municipality", nameNp: "मध्यविन्दु नगरपालिका", type: "municipality", wards: 15 },
        ],
      },
      {
        name: "Parwat",
        nameNp: "पर्वत",
        municipalities: [
          { name: "Bihadi Rural Municipality", nameNp: "विहादी गाउँपालिका", type: "rural", wards: 6 },
          { name: "Jaljala Rural Municipality", nameNp: "जलजला गाउँपालिका", type: "rural", wards: 9 },
          { name: "Kushma Municipality", nameNp: "कुश्मा नगरपालिका", type: "municipality", wards: 14 },
          { name: "Mahashila Rural Municipality", nameNp: "महाशिला गाउँपालिका", type: "rural", wards: 6 },
          { name: "Modi Rural Municipality", nameNp: "मोदी गाउँपालिका", type: "rural", wards: 8 },
          { name: "Paiyun Rural Municipality", nameNp: "पैयूं गाउँपालिका", type: "rural", wards: 7 },
          { name: "Phalewas Municipality", nameNp: "फलेवास नगरपालिका", type: "municipality", wards: 11 },
        ],
      },
      {
        name: "Syangja",
        nameNp: "स्याङग्जा",
        municipalities: [
          { name: "Aandhikhola Rural Municipality", nameNp: "आँधिखोला गाउँपालिका", type: "rural", wards: 6 },
          { name: "Arjun Chaupari Rural Municipality", nameNp: "अर्जुनचौपारी गाउँपालिका", type: "rural", wards: 6 },
          { name: "Bheerkot Municipality", nameNp: "भीरकोट नगरपालिका", type: "municipality", wards: 9 },
          { name: "Biruwa Rural Municipality", nameNp: "बिरुवा गाउँपालिका", type: "rural", wards: 8 },
          { name: "Chapakot Municipality", nameNp: "चापाकोट नगरपालिका", type: "municipality", wards: 10 },
          { name: "Galyang Municipality", nameNp: "गल्याङ नगरपालिका", type: "municipality", wards: 11 },
          { name: "Harinas Rural Municipality", nameNp: "हरिनास गाउँपालिका", type: "rural", wards: 7 },
          { name: "Kaligandaki Rural Municipality", nameNp: "कालीगण्डकी गाउँपालिका", type: "rural", wards: 7 },
          { name: "Phedikhola Rural Municipality", nameNp: "फेदीखोला गाउँपालिका", type: "rural", wards: 5 },
          { name: "Putalibazar Municipality", nameNp: "पुतलीबजार नगरपालिका", type: "municipality", wards: 14 },
          { name: "Waling Municipality", nameNp: "वालिङ नगरपालिका", type: "municipality", wards: 14 },
        ],
      },
      {
        name: "Tanahun",
        nameNp: "तनहुँ",
        municipalities: [
          { name: "AnbuKhaireni Rural Municipality", nameNp: "आँबुखैरेनी गाउँपालिका", type: "rural", wards: 6 },
          { name: "Bandipur Rural Municipality", nameNp: "वन्दिपुर गाउँपालिका", type: "rural", wards: 6 },
          { name: "Bhanu Municipality", nameNp: "भानु नगरपालिका", type: "municipality", wards: 13 },
          { name: "Bhimad Municipality", nameNp: "भिमाद नगरपालिका", type: "municipality", wards: 9 },
          { name: "Byas Municipality", nameNp: "व्यास नगरपालिका", type: "municipality", wards: 14 },
          { name: "Devghat Rural Municipality", nameNp: "देवघाट गाउँपालिका", type: "rural", wards: 5 },
          { name: "Ghiring Rural Municipality", nameNp: "घिरिङ गाउँपालिका", type: "rural", wards: 5 },
          { name: "Myagde Rural Municipality", nameNp: "म्याग्दे गाउँपालिका", type: "rural", wards: 7 },
          { name: "Rishing Rural Municipality", nameNp: "ऋषिङ्ग गाउँपालिका", type: "rural", wards: 8 },
          { name: "Suklagandaki Municipality", nameNp: "शुक्लागण्डकी नगरपालिका", type: "municipality", wards: 12 },
        ],
      },
    ],
  },
  {
    name: "Lumbini",
    nameNp: "लुम्बिनी",
    districts: [
      {
        name: "Arghakhanchi",
        nameNp: "अर्घाखाँची",
        municipalities: [
          { name: "Bhumikasthan Municipality", nameNp: "भूमिकास्थान नगरपालिका", type: "municipality", wards: 10 },
          { name: "Chhatradev Rural Municipality", nameNp: "छत्रदेव गाउँपालिका", type: "rural", wards: 8 },
          { name: "Malarani Rural Municipality", nameNp: "मालारानी गाउँपालिका", type: "rural", wards: 9 },
          { name: "Panini Rural Municipality", nameNp: "पाणिनी गाउँपालिका", type: "rural", wards: 8 },
          { name: "Sandhikharka Municipality", nameNp: "सन्धिखर्क नगरपालिका", type: "municipality", wards: 12 },
          { name: "Sitganga Municipality", nameNp: "शितगंगा नगरपालिका", type: "municipality", wards: 14 },
        ],
      },
      {
        name: "Banke",
        nameNp: "बाँके",
        municipalities: [
          { name: "Baijanath Rural Municipality", nameNp: "बैजनाथ गाउँपालिका", type: "rural", wards: 8 },
          { name: "Duduwa Rural Municipality", nameNp: "डुडुवा गाउँपालिका", type: "rural", wards: 6 },
          { name: "Janaki Rural Municipality", nameNp: "जानकी गाउँपालिका", type: "rural", wards: 6 },
          { name: "Khajura Rural Municipality", nameNp: "खजुरा गाउँपालिका", type: "rural", wards: 8 },
          { name: "Kohalpur Municipality", nameNp: "कोहलपुर नगरपालिका", type: "municipality", wards: 15 },
          { name: "Narainapur Rural Municipality", nameNp: "नरैनापुर गाउँपालिका", type: "rural", wards: 6 },
          { name: "Nepalgunj Sub-Metropolitan City", nameNp: "नेपालगंज उपमहानगरपालिका", type: "sub_metropolitan", wards: 23 },
          { name: "Rapti-Sonari Rural Municipality", nameNp: "राप्ती सोनारी गाउँपालिका", type: "rural", wards: 9 },
        ],
      },
      {
        name: "Bardiya",
        nameNp: "बर्दिया",
        municipalities: [
          { name: "Badhaiyatal Rural Municipality", nameNp: "बढैयाताल गाउँपालिका", type: "rural", wards: 9 },
          { name: "Barbardiya Municipality", nameNp: "बारबर्दिया नगरपालिका", type: "municipality", wards: 11 },
          { name: "Basgadhi Municipality", nameNp: "बाँसगढी नगरपालिका", type: "municipality", wards: 9 },
          { name: "Geruwa Rural Municipality", nameNp: "गेरुवा गाउँपालिका", type: "rural", wards: 6 },
          { name: "Gulariya Municipality", nameNp: "गुलरिया नगरपालिका", type: "municipality", wards: 12 },
          { name: "Madhuwan Municipality", nameNp: "मधुवन नगरपालिका", type: "municipality", wards: 9 },
          { name: "Rajapur Municipality", nameNp: "राजापुर नगरपालिका", type: "municipality", wards: 10 },
          { name: "Thakurbaba Municipality", nameNp: "ठाकुरबाबा नगरपालिका", type: "municipality", wards: 9 },
        ],
      },
      {
        name: "Dang",
        nameNp: "दाङ",
        municipalities: [
          { name: "Babai Rural Municipality", nameNp: "बबई गाउँपालिका", type: "rural", wards: 7 },
          { name: "Banglachuli Rural Municipality", nameNp: "बंगलाचुली गाउँपालिका", type: "rural", wards: 8 },
          { name: "Dangisharan Rural Municipality", nameNp: "दंगीशरण गाउँपालिका", type: "rural", wards: 7 },
          { name: "Gadhawa Rural Municipality", nameNp: "गढवा गाउँपालिका", type: "rural", wards: 8 },
          { name: "Ghorahi Sub-Metropolitan City", nameNp: "घोराही उपमहानगरपालिका", type: "sub_metropolitan", wards: 19 },
          { name: "Lamahi Municipality", nameNp: "लमही नगरपालिका", type: "municipality", wards: 9 },
          { name: "Rajpur Rural Municipality", nameNp: "राजपुर गाउँपालिका", type: "rural", wards: 7 },
          { name: "Rapti Rural Municipality", nameNp: "राप्ती गाउँपालिका", type: "rural", wards: 9 },
          { name: "Shantinagar Rural Municipality", nameNp: "शान्तिनगर गाउँपालिका", type: "rural", wards: 7 },
          { name: "Tulsipur Sub-Metropolitan City", nameNp: "तुल्सीपुर उपमहानगरपालिका", type: "sub_metropolitan", wards: 19 },
        ],
      },
      {
        name: "Eastern Rukum",
        nameNp: "पूर्वी रूकुम",
        municipalities: [
          { name: "Bhume Rural Municipality", nameNp: "भूमे गाउँपालिका", type: "rural", wards: 9 },
          { name: "Putha Uttarganga Rural Municipality", nameNp: "पुथा उत्तरगंगा गाउँपालिका", type: "rural", wards: 14 },
          { name: "Sisne Rural Municipality", nameNp: "सिस्ने गाउँपालिका", type: "rural", wards: 8 },
        ],
      },
      {
        name: "Gulmi",
        nameNp: "गुल्मी",
        municipalities: [
          { name: "Chandrakot Rural Municipality", nameNp: "चन्द्रकोट गाउँपालिका", type: "rural", wards: 8 },
          { name: "Chhatrakot Rural Municipality", nameNp: "छत्रकोट गाउँपालिका", type: "rural", wards: 6 },
          { name: "Dhurkot Rural Municipality", nameNp: "धुर्कोट गाउँपालिका", type: "rural", wards: 7 },
          { name: "Gulmidarbar Rural Municipality", nameNp: "गुल्मी दरबार गाउँपालिका", type: "rural", wards: 7 },
          { name: "Isma Rural Municipality", nameNp: "ईस्मा गाउँपालिका", type: "rural", wards: 6 },
          { name: "Kaligandaki Rural Municipality", nameNp: "कालीगण्डकी गाउँपालिका", type: "rural", wards: 7 },
          { name: "Madane Rural Municipality", nameNp: "मदाने गाउँपालिका", type: "rural", wards: 7 },
          { name: "Malika Rural Municipality", nameNp: "मालिका गाउँपालिका", type: "rural", wards: 8 },
          { name: "Musikot Municipality", nameNp: "मुसिकोट नगरपालिका", type: "municipality", wards: 9 },
          { name: "Resunga Municipality", nameNp: "रेसुङ्गा नगरपालिका", type: "municipality", wards: 14 },
          { name: "Rurukshetra Rural Municipality", nameNp: "रुरुक्षेत्र गाउँपालिका", type: "rural", wards: 6 },
          { name: "Satyawati Rural Municipality", nameNp: "सत्यवती गाउँपालिका", type: "rural", wards: 8 },
        ],
      },
      {
        name: "Kapilvastu",
        nameNp: "कपिलवस्तु",
        municipalities: [
          { name: "Banganga Municipality", nameNp: "बाणगंगा नगरपालिका", type: "municipality", wards: 11 },
          { name: "Bijaynagar Rural Municipality", nameNp: "विजयनगर गाउँपालिका", type: "rural", wards: 7 },
          { name: "Buddhabhumi Municipality", nameNp: "बुद्धभुमी नगरपालिका", type: "municipality", wards: 10 },
          { name: "Kapilvastu Municipality", nameNp: "कपिलवस्तु नगरपालिका", type: "municipality", wards: 12 },
          { name: "Krishnanagar Municipality", nameNp: "कृष्णनगर नगरपालिका", type: "municipality", wards: 12 },
          { name: "Maharajgunj Municipality", nameNp: "महाराजगंज नगरपालिका", type: "municipality", wards: 11 },
          { name: "Mayadevi Rural Municipality", nameNp: "मायादेवी गाउँपालिका", type: "rural", wards: 8 },
          { name: "Shivaraj Municipality", nameNp: "शिवराज नगरपालिका", type: "municipality", wards: 11 },
          { name: "Suddhodan Rural Municipality", nameNp: "सुद्धोधन गाउँपालिका", type: "rural", wards: 6 },
          { name: "Yashodhara Rural Municipality", nameNp: "यसोधरा गाउँपालिका", type: "rural", wards: 8 },
        ],
      },
      {
        name: "Palpa",
        nameNp: "पाल्पा",
        municipalities: [
          { name: "Bagnaskali Rural Municipality", nameNp: "बगनासकाली गाउँपालिका", type: "rural", wards: 9 },
          { name: "Mathagadhi Rural Municipality", nameNp: "माथागढी गाउँपालिका", type: "rural", wards: 8 },
          { name: "Nisdi Rural Municipality", nameNp: "निस्दी गाउँपालिका", type: "rural", wards: 7 },
          { name: "Purbakhola Rural Municipality", nameNp: "पूर्वखोला गाउँपालिका", type: "rural", wards: 6 },
          { name: "Rainadevi Chhahara Rural Municipality", nameNp: "रैनादेवी छहरा गाउँपालिका", type: "rural", wards: 8 },
          { name: "Rambha Rural Municipality", nameNp: "रम्भा गाउँपालिका", type: "rural", wards: 5 },
          { name: "Rampur Municipality", nameNp: "रामपुर नगरपालिका", type: "municipality", wards: 10 },
          { name: "Ripdikot Rural Municipality", nameNp: "रिब्दिकोट गाउँपालिका", type: "rural", wards: 8 },
          { name: "Tansen Municipality", nameNp: "तानसेन नगरपालिका", type: "municipality", wards: 14 },
          { name: "Tinahu Rural Municipality", nameNp: "तिनाउ गाउँपालिका", type: "rural", wards: 6 },
        ],
      },
      {
        name: "Parasi",
        nameNp: "परासी",
        municipalities: [
          { name: "Bardaghat Municipality", nameNp: "बर्दघाट नगरपालिका", type: "municipality", wards: 16 },
          { name: "Palhi Nandan Rural Municipality", nameNp: "पाल्हीनन्दन गाउँपालिका", type: "rural", wards: 6 },
          { name: "Pratappur Rural Municipality", nameNp: "प्रतापपुर गाउँपालिका", type: "rural", wards: 9 },
          { name: "Ramgram Municipality", nameNp: "रामग्राम नगरपालिका", type: "municipality", wards: 18 },
          { name: "Sarawal Rural Municipality", nameNp: "सरावल गाउँपालिका", type: "rural", wards: 7 },
          { name: "Sunwal Municipality", nameNp: "सुनवल नगरपालिका", type: "municipality", wards: 13 },
          { name: "Susta Rural Municipality", nameNp: "सुस्ता गाउँपालिका", type: "rural", wards: 5 },
        ],
      },
      {
        name: "Pyuthan",
        nameNp: "प्युठान",
        municipalities: [
          { name: "Ayirawati Rural Municipality", nameNp: "ऐरावती गाउँपालिका", type: "rural", wards: 6 },
          { name: "Gaumukhi Rural Municipality", nameNp: "गौमुखी गाउँपालिका", type: "rural", wards: 7 },
          { name: "Jhimruk Rural Municipality", nameNp: "झिमरुक गाउँपालिका", type: "rural", wards: 8 },
          { name: "Mallarani Rural Municipality", nameNp: "मल्लरानी गाउँपालिका", type: "rural", wards: 5 },
          { name: "Mandavi Rural Municipality", nameNp: "माण्डवी गाउँपालिका", type: "rural", wards: 5 },
          { name: "Naubahini Rural Municipality", nameNp: "नौवहिनी गाउँपालिका", type: "rural", wards: 8 },
          { name: "Pyuthan Municipality", nameNp: "प्यूठान नगरपालिका", type: "municipality", wards: 10 },
          { name: "Sarumarani Rural Municipality", nameNp: "सरुमारानी गाउँपालिका", type: "rural", wards: 6 },
          { name: "Sworgadwari Municipality", nameNp: "स्वर्गद्वारी नगरपालिका", type: "municipality", wards: 9 },
        ],
      },
      {
        name: "Rolpa",
        nameNp: "रोल्पा",
        municipalities: [
          { name: "GangaDev Rural Municipality", nameNp: "गंगादेव गाउँपालिका", type: "rural", wards: 7 },
          { name: "Lungri Rural Municipality", nameNp: "लुङग्री गाउँपालिका", type: "rural", wards: 7 },
          { name: "Madi Rural Municipality", nameNp: "माडी गाउँपालिका", type: "rural", wards: 6 },
          { name: "Pariwartan Rural Municipality", nameNp: "परिवर्तन गाउँपालिका", type: "rural", wards: 6 },
          { name: "Rolpa Municipality", nameNp: "रोल्पा नगरपालिका", type: "municipality", wards: 10 },
          { name: "Runtigadi Rural Municipality", nameNp: "रुन्टीगढी गाउँपालिका", type: "rural", wards: 9 },
          { name: "Sunchhahari Rural Municipality", nameNp: "सुनछहरी गाउँपालिका", type: "rural", wards: 7 },
          { name: "Sunil Smiriti Rural Municipality", nameNp: "सुनिल स्मृति गाउँपालिका", type: "rural", wards: 8 },
          { name: "Thawang Rural Municipality", nameNp: "थवाङ गाउँपालिका", type: "rural", wards: 5 },
          { name: "Triveni Rural Municipality", nameNp: "त्रिवेणी गाउँपालिका", type: "rural", wards: 7 },
        ],
      },
      {
        name: "Rupandehi",
        nameNp: "रुपन्देही",
        municipalities: [
          { name: "Butwal Sub-Metropolitan City", nameNp: "बुटवल उपमहानगरपालिका", type: "sub_metropolitan", wards: 19 },
          { name: "Devdaha Municipality", nameNp: "देवदह नगरपालिका", type: "municipality", wards: 12 },
          { name: "Gaidahawa Rural Municipality", nameNp: "गैडहवा गाउँपालिका", type: "rural", wards: 9 },
          { name: "Kanchan Rural Municipality", nameNp: "कन्चन गाउँपालिका", type: "rural", wards: 5 },
          { name: "Kotahimai Rural Municipality", nameNp: "कोटहीमाई गाउँपालिका", type: "rural", wards: 7 },
          { name: "Lumbini Sanskritik Municipality", nameNp: "लुम्बिनी सांस्कृतिक नगरपालिका", type: "municipality", wards: 13 },
          { name: "Marchawari Rural Municipality", nameNp: "मर्चवारी गाउँपालिका", type: "rural", wards: 7 },
          { name: "Mayadevi Rural Municipality", nameNp: "मायादेवी गाउँपालिका", type: "rural", wards: 8 },
          { name: "Omsatiya Rural Municipality", nameNp: "ओमसतिया गाउँपालिका", type: "rural", wards: 6 },
          { name: "Rohini Rural Municipality", nameNp: "रोहिणी गाउँपालिका", type: "rural", wards: 7 },
          { name: "Sainamaina Municipality", nameNp: "सैनामैना नगरपालिका", type: "municipality", wards: 11 },
          { name: "Sammarimai Rural Municipality", nameNp: "सम्मरीमाई गाउँपालिका", type: "rural", wards: 7 },
          { name: "Siddharthanagar Municipality", nameNp: "सिद्धार्थनगर नगरपालिका", type: "municipality", wards: 13 },
          { name: "Siyari Rural Municipality", nameNp: "सियारी गाउँपालिका", type: "rural", wards: 7 },
          { name: "Suddodhan Rural Municipality", nameNp: "शुद्धोधन गाउँपालिका", type: "rural", wards: 7 },
          { name: "Tilottama Municipality", nameNp: "तिलोत्तमा नगरपालिका", type: "municipality", wards: 17 },
        ],
      },
    ],
  },
  {
    name: "Karnali",
    nameNp: "कर्णाली",
    districts: [
      {
        name: "Dailekh",
        nameNp: "दैलेख",
        municipalities: [
          { name: "Aathabis Municipality", nameNp: "आठबीस नगरपालिका", type: "municipality", wards: 9 },
          { name: "Bhagawatimai Rural Municipality", nameNp: "भगवतीमाई गाउँपालिका", type: "rural", wards: 7 },
          { name: "Bhairabi Rural Municipality", nameNp: "भैरवी गाउँपालिका", type: "rural", wards: 7 },
          { name: "Chamunda Bindrasaini Municipality", nameNp: "चामुण्डा विन्द्रासैनी नगरपालिका", type: "municipality", wards: 9 },
          { name: "Dullu Municipality", nameNp: "दुल्लु नगरपालिका", type: "municipality", wards: 13 },
          { name: "Dungeshwar Rural Municipality", nameNp: "डुंगेश्वर गाउँपालिका", type: "rural", wards: 6 },
          { name: "Gurans Rural Municipality", nameNp: "गुराँस गाउँपालिका", type: "rural", wards: 8 },
          { name: "Mahabu Rural Municipality", nameNp: "महावु गाउँपालिका", type: "rural", wards: 6 },
          { name: "Narayan Municipality", nameNp: "नारायण नगरपालिका", type: "municipality", wards: 11 },
          { name: "Naumule Rural Municipality", nameNp: "नौमुले गाउँपालिका", type: "rural", wards: 8 },
          { name: "Thantikandh Rural Municipality", nameNp: "ठाँटीकाँध गाउँपालिका", type: "rural", wards: 6 },
        ],
      },
      {
        name: "Dolpa",
        nameNp: "डोल्पा",
        municipalities: [
          { name: "Chharka Tongsong Rural Municipality", nameNp: "छार्का ताङसोङ गाउँपालिका", type: "rural", wards: 6 },
          { name: "Dolpo Buddha Rural Municipality", nameNp: "डोल्पो बुद्ध गाउँपालिका", type: "rural", wards: 6 },
          { name: "Jagadulla Rural Municipality", nameNp: "जगदुल्ला गाउँपालिका", type: "rural", wards: 6 },
          { name: "Kaike Rural Municipality", nameNp: "काईके गाउँपालिका", type: "rural", wards: 7 },
          { name: "Mudkechula Rural Municipality", nameNp: "मुड्केचुला गाउँपालिका", type: "rural", wards: 9 },
          { name: "She Phoksundo Rural Municipality", nameNp: "शे फोक्सुन्डो गाउँपालिका", type: "rural", wards: 9 },
          { name: "Thuli Bheri Municipality", nameNp: "ठूली भेरी नगरपालिका", type: "municipality", wards: 11 },
          { name: "Tripurasundari Municipality", nameNp: "त्रिपुरासुन्दरी नगरपालिका", type: "municipality", wards: 11 },
        ],
      },
      {
        name: "Humla",
        nameNp: "हुम्ला",
        municipalities: [
          { name: "Adanchuli Rural Municipality", nameNp: "अदानचुली गाउँपालिका", type: "rural", wards: 6 },
          { name: "Chankheli Rural Municipality", nameNp: "चंखेली गाउँपालिका", type: "rural", wards: 6 },
          { name: "Kharpunath Rural Municipality", nameNp: "खार्पुनाथ गाउँपालिका", type: "rural", wards: 5 },
          { name: "Namkha Rural Municipality", nameNp: "नाम्खा गाउँपालिका", type: "rural", wards: 6 },
          { name: "Sarkegad Rural Municipality", nameNp: "सर्केगाड गाउँपालिका", type: "rural", wards: 8 },
          { name: "Simkot Rural Municipality", nameNp: "सिमकोट गाउँपालिका", type: "rural", wards: 8 },
          { name: "Tanjakot Rural Municipality", nameNp: "ताँजाकोट गाउँपालिका", type: "rural", wards: 5 },
        ],
      },
      {
        name: "Jajarkot",
        nameNp: "जाजरकोट",
        municipalities: [
          { name: "Barekot Rural Municipality", nameNp: "बारेकोट गाउँपालिका", type: "rural", wards: 9 },
          { name: "Bheri Municipality", nameNp: "भेरी नगरपालिका", type: "municipality", wards: 13 },
          { name: "Chhedagad Municipality", nameNp: "छेडागाड नगरपालिका", type: "municipality", wards: 13 },
          { name: "Junichande Rural Municipality", nameNp: "जुनीचाँदे गाउँपालिका", type: "rural", wards: 11 },
          { name: "Kuse Rural Municipality", nameNp: "कुसे गाउँपालिका", type: "rural", wards: 9 },
          { name: "Nalgad Municipality", nameNp: "नलगाड नगरपालिका", type: "municipality", wards: 13 },
          { name: "Shivalaya Rural Municipality", nameNp: "शिवालय गाउँपालिका", type: "rural", wards: 9 },
        ],
      },
      {
        name: "Jumla",
        nameNp: "जुम्ला",
        municipalities: [
          { name: "Chandannath Municipality", nameNp: "चन्दननाथ नगरपालिका", type: "municipality", wards: 10 },
          { name: "Guthichaur Rural Municipality", nameNp: "गुठिचौर गाउँपालिका", type: "rural", wards: 5 },
          { name: "Hima Rural Municipality", nameNp: "हिमा गाउँपालिका", type: "rural", wards: 7 },
          { name: "Kanaka Sundari Rural Municipality", nameNp: "कनकासुन्दरी गाउँपालिका", type: "rural", wards: 8 },
          { name: "Patarasi Rural Municipality", nameNp: "पातारासी गाउँपालिका", type: "rural", wards: 7 },
          { name: "Sinja Rural Municipality", nameNp: "सिंजा गाउँपालिका", type: "rural", wards: 6 },
          { name: "Tatopani Rural Municipality", nameNp: "तातोपानी गाउँपालिका", type: "rural", wards: 8 },
          { name: "Tila Rural Municipality", nameNp: "तिला गाउँपालिका", type: "rural", wards: 9 },
        ],
      },
      {
        name: "Kalikot",
        nameNp: "कालिकोट",
        municipalities: [
          { name: "Khandachakra Municipality", nameNp: "खाँडाचक्र नगरपालिका", type: "municipality", wards: 11 },
          { name: "Mahawai Rural Municipality", nameNp: "महावै गाउँपालिका", type: "rural", wards: 7 },
          { name: "Narharinath Rural Municipality", nameNp: "नरहरिनाथ गाउँपालिका", type: "rural", wards: 9 },
          { name: "Pachaljharana Rural Municipality", nameNp: "पचालझरना गाउँपालिका", type: "rural", wards: 9 },
          { name: "Palata Rural Municipality", nameNp: "पलाता गाउँपालिका", type: "rural", wards: 9 },
          { name: "Raskot Municipality", nameNp: "रास्कोट नगरपालिका", type: "municipality", wards: 9 },
          { name: "Sanni Triveni Rural Municipality", nameNp: "सान्नी त्रिवेणी गाउँपालिका", type: "rural", wards: 9 },
          { name: "Shubha Kalika Rural Municipality", nameNp: "शुभ कालीका गाउँपालिका", type: "rural", wards: 8 },
          { name: "Tilagufa Municipality", nameNp: "तिलागुफा नगरपालिका", type: "municipality", wards: 11 },
        ],
      },
      {
        name: "Mugu",
        nameNp: "मुगु",
        municipalities: [
          { name: "Chhayanath Rara Municipality", nameNp: "छायाँनाथ रारा नगरपालिका", type: "municipality", wards: 14 },
          { name: "Khatyad Rural Municipality", nameNp: "खत्याड गाउँपालिका", type: "rural", wards: 11 },
          { name: "Mugum Karmarong Rural Municipality", nameNp: "मुगुम कार्मारोंग गाउँपालिका", type: "rural", wards: 9 },
          { name: "Soru Rural Municipality", nameNp: "सोरु गाउँपालिका", type: "rural", wards: 11 },
        ],
      },
      {
        name: "Salyan",
        nameNp: "सल्यान",
        municipalities: [
          { name: "Bagchaur Municipality", nameNp: "बागचौर नगरपालिका", type: "municipality", wards: 12 },
          { name: "Bangad Kupinde Municipality", nameNp: "बनगाड कुपिण्डे नगरपालिका", type: "municipality", wards: 12 },
          { name: "Chhatreshwari Rural Municipality", nameNp: "छत्रेश्वरी गाउँपालिका", type: "rural", wards: 7 },
          { name: "Darma Rural Municipality", nameNp: "दार्मा गाउँपालिका", type: "rural", wards: 6 },
          { name: "Kalimati Rural Municipality", nameNp: "कालिमाटी गाउँपालिका", type: "rural", wards: 7 },
          { name: "Kapurkot Rural Municipality", nameNp: "कपुरकोट गाउँपालिका", type: "rural", wards: 6 },
          { name: "Kumakh Rural Municipality", nameNp: "कुमाख गाउँपालिका", type: "rural", wards: 7 },
          { name: "Shaarda Municipality", nameNp: "शारदा नगरपालिका", type: "municipality", wards: 15 },
          { name: "Siddha Kumakh Rural Municipality", nameNp: "सिद्ध कुमाख गाउँपालिका", type: "rural", wards: 5 },
          { name: "Triveni Rural Municipality", nameNp: "त्रिवेणी गाउँपालिका", type: "rural", wards: 6 },
        ],
      },
      {
        name: "Surkhet",
        nameNp: "सुर्खेत",
        municipalities: [
          { name: "Barahatal Rural Municipality", nameNp: "बराहताल गाउँपालिका", type: "rural", wards: 10 },
          { name: "Bheriganga Municipality", nameNp: "भेरीगंगा नगरपालिका", type: "municipality", wards: 13 },
          { name: "Birendranagar Municipality", nameNp: "बीरेन्द्रनगर नगरपालिका", type: "municipality", wards: 16 },
          { name: "Chaukune Rural Municipality", nameNp: "चौकुने गाउँपालिका", type: "rural", wards: 10 },
          { name: "Chingad Rural Municipality", nameNp: "चिङ्गाड गाउँपालिका", type: "rural", wards: 6 },
          { name: "Gurbhakot Municipality", nameNp: "गुर्भाकोट नगरपालिका", type: "municipality", wards: 14 },
          { name: "Lekbeshi Municipality", nameNp: "लेकवेशी नगरपालिका", type: "municipality", wards: 10 },
          { name: "Panchapuri Municipality", nameNp: "पञ्चपुरी नगरपालिका", type: "municipality", wards: 11 },
          { name: "Simta Rural Municipality", nameNp: "सिम्ता गाउँपालिका", type: "rural", wards: 9 },
        ],
      },
      {
        name: "Western Rukum",
        nameNp: "रुकुम पश्चिम",
        municipalities: [
          { name: "Aathabiskot Municipality", nameNp: "आठबिसकोट नगरपालिका", type: "municipality", wards: 14 },
          { name: "Banphikot Rural Municipality", nameNp: "बाँफिकोट गाउँपालिका", type: "rural", wards: 10 },
          { name: "Chaurjahari Municipality", nameNp: "चौरजहारी नगरपालिका", type: "municipality", wards: 14 },
          { name: "Musikot Municipality", nameNp: "मुसिकोट नगरपालिका", type: "municipality", wards: 14 },
          { name: "SaniBheri Rural Municipality", nameNp: "सानी भेरी गाउँपालिका", type: "rural", wards: 11 },
          { name: "Triveni Rural Municipality", nameNp: "त्रिवेणी गाउँपालिका", type: "rural", wards: 10 },
        ],
      },
    ],
  },
  {
    name: "Sudurpaschim",
    nameNp: "सुदुरपश्चिम",
    districts: [
      {
        name: "Acham",
        nameNp: "अछाम",
        municipalities: [
          { name: "Bannigadi Jayagad Rural Municipality", nameNp: "बान्निगढी जयगढ गाउँपालिका", type: "rural", wards: 6 },
          { name: "Chaurpati Rural Municipality", nameNp: "चौरपाटी गाउँपालिका", type: "rural", wards: 7 },
          { name: "Dhakari Rural Municipality", nameNp: "ढकारी गाउँपालिका", type: "rural", wards: 8 },
          { name: "Kamalbazar Municipality", nameNp: "कमलबजार नगरपालिका", type: "municipality", wards: 10 },
          { name: "Mangalsen Municipality", nameNp: "मंगलसेन नगरपालिका", type: "municipality", wards: 14 },
          { name: "Mellekh Rural Municipality", nameNp: "मेल्लेख गाउँपालिका", type: "rural", wards: 8 },
          { name: "Panchadewal Binayak Municipality", nameNp: "पन्चदेवल विनायक नगरपालिका", type: "municipality", wards: 9 },
          { name: "Ramaroshan Rural Municipality", nameNp: "रामारोशन गाउँपालिका", type: "rural", wards: 7 },
          { name: "Sanfebagar Municipality", nameNp: "साँफेबगर नगरपालिका", type: "municipality", wards: 14 },
          { name: "Turmakhand Rural Municipality", nameNp: "तुर्माखाँद गाउँपालिका", type: "rural", wards: 8 },
        ],
      },
      {
        name: "Baitadi",
        nameNp: "बैतडी",
        municipalities: [
          { name: "Dashrathchanda Municipality", nameNp: "दशरथचन्द नगरपालिका", type: "municipality", wards: 11 },
          { name: "Dilashaini Rural Municipality", nameNp: "डीलासैनी गाउँपालिका", type: "rural", wards: 7 },
          { name: "Dogdakedar Rural Municipality", nameNp: "दोगडाकेदार गाउँपालिका", type: "rural", wards: 8 },
          { name: "Melauli Municipality", nameNp: "मेलौली नगरपालिका", type: "municipality", wards: 9 },
          { name: "Pancheshwar Rural Municipality", nameNp: "पञ्चेश्वर गाउँपालिका", type: "rural", wards: 6 },
          { name: "Patan Municipality", nameNp: "पाटन नगरपालिका", type: "municipality", wards: 10 },
          { name: "Purchaudi Municipality", nameNp: "पुर्चौडी नगरपालिका", type: "municipality", wards: 10 },
          { name: "Shivanath Rural Municipality", nameNp: "शिवनाथ गाउँपालिका", type: "rural", wards: 6 },
          { name: "Sigas Rural Municipality", nameNp: "सिगास गाउँपालिका", type: "rural", wards: 9 },
          { name: "Surnaya Rural Municipality", nameNp: "सुर्नया गाउँपालिका", type: "rural", wards: 8 },
        ],
      },
      {
        name: "Bajhang",
        nameNp: "बझाङ",
        municipalities: [
          { name: "Bitthadchir Rural Municipality", nameNp: "वित्थडचिर गाउँपालिका", type: "rural", wards: 9 },
          { name: "Bungal Municipality", nameNp: "बुंगल नगरपालिका", type: "municipality", wards: 11 },
          { name: "Chhabis Pathibhera Rural Municipality", nameNp: "छबिसपाथिभेरा गाउँपालिका", type: "rural", wards: 7 },
          { name: "Durgathali Rural Municipality", nameNp: "दुर्गाथली गाउँपालिका", type: "rural", wards: 7 },
          { name: "Jayaprithvi Municipality", nameNp: "जयपृथ्वी नगरपालिका", type: "municipality", wards: 11 },
          { name: "Kedarsyu Rural Municipality", nameNp: "केदारस्युँ गाउँपालिका", type: "rural", wards: 9 },
          { name: "Khaptadchhanna Rural Municipality", nameNp: "खप्तडछान्ना गाउँपालिका", type: "rural", wards: 7 },
          { name: "Masta Rural Municipality", nameNp: "मष्टा गाउँपालिका", type: "rural", wards: 7 },
          { name: "Saipal Rural Municipality", nameNp: "साइपाल गाउँपालिका", type: "rural", wards: 5 },
          { name: "Surma Rural Municipality", nameNp: "सूर्मा गाउँपालिका", type: "rural", wards: 5 },
          { name: "Talkot Rural Municipality", nameNp: "तलकोट गाउँपालिका", type: "rural", wards: 7 },
          { name: "Thalara Rural Municipality", nameNp: "थलारा गाउँपालिका", type: "rural", wards: 9 },
        ],
      },
      {
        name: "Bajura",
        nameNp: "बाजुरा",
        municipalities: [
          { name: "Badimalika Municipality", nameNp: "बडीमालिका नगरपालिका", type: "municipality", wards: 9 },
          { name: "Budhiganga Municipality", nameNp: "बुढीगंगा नगरपालिका", type: "municipality", wards: 10 },
          { name: "Budhinanda Municipality", nameNp: "बुढीनन्दा नगरपालिका", type: "municipality", wards: 10 },
          { name: "Gaumul Rural Municipality", nameNp: "गौमुल गाउँपालिका", type: "rural", wards: 6 },
          { name: "Himali Rural Municipality", nameNp: "हिमाली गाउँपालिका", type: "rural", wards: 7 },
          { name: "Jagannath Rural Municipality", nameNp: "जगन्‍नाथ गाउँपालिका", type: "rural", wards: 6 },
          { name: "Khaptad Chhededaha Rural Municipality", nameNp: "खप्तड छेडेदह गाउँपालिका", type: "rural", wards: 7 },
          { name: "Swami Kartik Khapar Rural Municipality", nameNp: "स्वामीकार्तिक खापर गाउँपालिका", type: "rural", wards: 5 },
          { name: "Triveni Municipality", nameNp: "त्रिवेणी नगरपालिका", type: "municipality", wards: 9 },
        ],
      },
      {
        name: "Dadeldhura",
        nameNp: "डडेलधुरा",
        municipalities: [
          { name: "Aalitaal Rural Municipality", nameNp: "आलिताल गाउँपालिका", type: "rural", wards: 8 },
          { name: "Ajaymeru Rural Municipality", nameNp: "अजयमेरु गाउँपालिका", type: "rural", wards: 6 },
          { name: "Amargadhi Municipality", nameNp: "अमरगढी नगरपालिका", type: "municipality", wards: 11 },
          { name: "Bhageshwar Rural Municipality", nameNp: "भागेश्वर गाउँपालिका", type: "rural", wards: 5 },
          { name: "Ganyapadhura Rural Municipality", nameNp: "गन्यापधुरा गाउँपालिका", type: "rural", wards: 5 },
          { name: "Navadurga Rural Municipality", nameNp: "नवदुर्गा गाउँपालिका", type: "rural", wards: 5 },
          { name: "Parshuram Municipality", nameNp: "परशुराम नगरपालिका", type: "municipality", wards: 12 },
        ],
      },
      {
        name: "Darchula",
        nameNp: "दार्चुला",
        municipalities: [
          { name: "Apihimal Rural Municipality", nameNp: "अपिहिमाल गाउँपालिका", type: "rural", wards: 6 },
          { name: "Duhun Rural Municipality", nameNp: "दुहुँ गाउँपालिका", type: "rural", wards: 5 },
          { name: "Lekam Rural Municipality", nameNp: "लेकम गाउँपालिका", type: "rural", wards: 6 },
          { name: "Mahakali Municipality", nameNp: "महाकाली नगरपालिका", type: "municipality", wards: 9 },
          { name: "Malikarjun Rural Municipality", nameNp: "मालिकार्जुन गाउँपालिका", type: "rural", wards: 8 },
          { name: "Marma Rural Municipality", nameNp: "मार्मा गाउँपालिका", type: "rural", wards: 6 },
          { name: "Naugad Rural Municipality", nameNp: "नौगाड गाउँपालिका", type: "rural", wards: 6 },
          { name: "Shailyashikhar Municipality", nameNp: "शैल्यशिखर नगरपालिका", type: "municipality", wards: 9 },
          { name: "Vyans Rural Municipality", nameNp: "ब्याँस गाउँपालिका", type: "rural", wards: 6 },
        ],
      },
      {
        name: "Doti",
        nameNp: "डोटी",
        municipalities: [
          { name: "Aadarsha Rural Municipality", nameNp: "आदर्श गाउँपालिका", type: "rural", wards: 7 },
          { name: "Badikedar Rural Municipality", nameNp: "बडीकेदार गाउँपालिका", type: "rural", wards: 5 },
          { name: "Bogatan-Phudsil Rural Municipality", nameNp: "बोगटान फुड्सिल गाउँपालिका", type: "rural", wards: 7 },
          { name: "Dipayal Silgadhi Municipality", nameNp: "दिपायल सिलगढी नगरपालिका", type: "municipality", wards: 9 },
          { name: "Jorayal Rural Municipality", nameNp: "जोरायल गाउँपालिका", type: "rural", wards: 6 },
          { name: "K.I.Singh Rural Municipality", nameNp: "के.आई.सिं. गाउँपालिका", type: "rural", wards: 7 },
          { name: "Purbichauki Rural Municipality", nameNp: "पूर्वीचौकी गाउँपालिका", type: "rural", wards: 7 },
          { name: "Sayal Rural Municipality", nameNp: "सायल गाउँपालिका", type: "rural", wards: 6 },
          { name: "Shikhar Municipality", nameNp: "शिखर नगरपालिका", type: "municipality", wards: 11 },
        ],
      },
      {
        name: "Kailali",
        nameNp: "कैलाली",
        municipalities: [
          { name: "Bardagoriya Rural Municipality", nameNp: "बर्दगोरिया गाउँपालिका", type: "rural", wards: 6 },
          { name: "Bhajni Municipality", nameNp: "भजनी नगरपालिका", type: "municipality", wards: 9 },
          { name: "Chure Rural Municipality", nameNp: "चुरे गाउँपालिका", type: "rural", wards: 6 },
          { name: "Dhangadhi Sub-Metropolitan City", nameNp: "धनगढी उपमहानगरपालिका", type: "sub_metropolitan", wards: 19 },
          { name: "Gauriganga Municipality", nameNp: "गौरीगंगा नगरपालिका", type: "municipality", wards: 11 },
          { name: "Ghodaghodi Municipality", nameNp: "घोडाघोडी नगरपालिका", type: "municipality", wards: 12 },
          { name: "Godawari Municipality", nameNp: "गोदावरी नगरपालिका", type: "municipality", wards: 12 },
          { name: "Janaki Rural Municipality", nameNp: "जानकी गाउँपालिका", type: "rural", wards: 9 },
          { name: "Joshipur Rural Municipality", nameNp: "जोशीपुर गाउँपालिका", type: "rural", wards: 7 },
          { name: "Kailari Rural Municipality", nameNp: "कैलारी गाउँपालिका", type: "rural", wards: 9 },
          { name: "Lamkichuha Municipality", nameNp: "लम्कीचुहा नगरपालिका", type: "municipality", wards: 10 },
          { name: "Mohanyal Rural Municipality", nameNp: "मोहन्याल गाउँपालिका", type: "rural", wards: 7 },
          { name: "Tikapur Municipality", nameNp: "टिकापुर नगरपालिका", type: "municipality", wards: 9 },
        ],
      },
      {
        name: "Kanchanpur",
        nameNp: "कञ्चनपुर",
        municipalities: [
          { name: "Bedkot Municipality", nameNp: "वेदकोट नगरपालिका", type: "municipality", wards: 10 },
          { name: "Belauri Municipality", nameNp: "बेलौरी नगरपालिका", type: "municipality", wards: 10 },
          { name: "Beldandi Rural Municipality", nameNp: "बेलडाडी गाउँपालिका", type: "rural", wards: 5 },
          { name: "Bhimdatta Municipality", nameNp: "भीमदत्त नगरपालिका", type: "municipality", wards: 19 },
          { name: "Krishnapur Municipality", nameNp: "कृष्णपुर नगरपालिका", type: "municipality", wards: 9 },
          { name: "Laljhadi Rural Municipality", nameNp: "लालझाडी गाउँपालिका", type: "rural", wards: 6 },
          { name: "Mahakali Municipality", nameNp: "माहाकाली नगरपालिका", type: "municipality", wards: 10 },
          { name: "Punarbas Municipality", nameNp: "पुर्नवास नगरपालिका", type: "municipality", wards: 11 },
          { name: "Shuklaphanta Municipality", nameNp: "शुक्लाफाँटा नगरपालिका", type: "municipality", wards: 12 },
        ],
      },
    ],
  },];

export function findProvince(name: string): Province | undefined {
  return PROVINCES.find((p) => p.name === name);
}

export function districtsOf(provinceName: string): District[] {
  return findProvince(provinceName)?.districts ?? [];
}

export function municipalitiesOf(
  provinceName: string,
  districtName: string
): Municipality[] {
  return (
    districtsOf(provinceName).find((d) => d.name === districtName)
      ?.municipalities ?? []
  );
}

/** Ward count for a local level, or null when it is not in the dataset. */
export function wardsOf(
  provinceName: string,
  districtName: string,
  municipalityName: string
): number | null {
  return (
    municipalitiesOf(provinceName, districtName).find(
      (m) => m.name === municipalityName
    )?.wards ?? null
  );
}
